// Code generated by ent, DO NOT EDIT.

package supportticketattachment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the supportticketattachment type in the database.
	Label = "support_ticket_attachment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMessageID holds the string denoting the message_id field in the database.
	FieldMessageID = "message_id"
	// FieldUploaderID holds the string denoting the uploader_id field in the database.
	FieldUploaderID = "uploader_id"
	// FieldOriginalName holds the string denoting the original_name field in the database.
	FieldOriginalName = "original_name"
	// FieldStorageKey holds the string denoting the storage_key field in the database.
	FieldStorageKey = "storage_key"
	// FieldMediaType holds the string denoting the media_type field in the database.
	FieldMediaType = "media_type"
	// FieldSizeBytes holds the string denoting the size_bytes field in the database.
	FieldSizeBytes = "size_bytes"
	// FieldDeleteAfter holds the string denoting the delete_after field in the database.
	FieldDeleteAfter = "delete_after"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldDeleteReason holds the string denoting the delete_reason field in the database.
	FieldDeleteReason = "delete_reason"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeMessage holds the string denoting the message edge name in mutations.
	EdgeMessage = "message"
	// EdgeUploader holds the string denoting the uploader edge name in mutations.
	EdgeUploader = "uploader"
	// EdgeDeletedByUser holds the string denoting the deleted_by_user edge name in mutations.
	EdgeDeletedByUser = "deleted_by_user"
	// Table holds the table name of the supportticketattachment in the database.
	Table = "support_ticket_attachments"
	// MessageTable is the table that holds the message relation/edge.
	MessageTable = "support_ticket_attachments"
	// MessageInverseTable is the table name for the SupportTicketMessage entity.
	// It exists in this package in order to avoid circular dependency with the "supportticketmessage" package.
	MessageInverseTable = "support_ticket_messages"
	// MessageColumn is the table column denoting the message relation/edge.
	MessageColumn = "message_id"
	// UploaderTable is the table that holds the uploader relation/edge.
	UploaderTable = "support_ticket_attachments"
	// UploaderInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UploaderInverseTable = "users"
	// UploaderColumn is the table column denoting the uploader relation/edge.
	UploaderColumn = "uploader_id"
	// DeletedByUserTable is the table that holds the deleted_by_user relation/edge.
	DeletedByUserTable = "support_ticket_attachments"
	// DeletedByUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	DeletedByUserInverseTable = "users"
	// DeletedByUserColumn is the table column denoting the deleted_by_user relation/edge.
	DeletedByUserColumn = "deleted_by"
)

// Columns holds all SQL columns for supportticketattachment fields.
var Columns = []string{
	FieldID,
	FieldMessageID,
	FieldUploaderID,
	FieldOriginalName,
	FieldStorageKey,
	FieldMediaType,
	FieldSizeBytes,
	FieldDeleteAfter,
	FieldDeletedAt,
	FieldDeletedBy,
	FieldDeleteReason,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OriginalNameValidator is a validator for the "original_name" field. It is called by the builders before save.
	OriginalNameValidator func(string) error
	// StorageKeyValidator is a validator for the "storage_key" field. It is called by the builders before save.
	StorageKeyValidator func(string) error
	// MediaTypeValidator is a validator for the "media_type" field. It is called by the builders before save.
	MediaTypeValidator func(string) error
	// DeleteReasonValidator is a validator for the "delete_reason" field. It is called by the builders before save.
	DeleteReasonValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the SupportTicketAttachment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMessageID orders the results by the message_id field.
func ByMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessageID, opts...).ToFunc()
}

// ByUploaderID orders the results by the uploader_id field.
func ByUploaderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploaderID, opts...).ToFunc()
}

// ByOriginalName orders the results by the original_name field.
func ByOriginalName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalName, opts...).ToFunc()
}

// ByStorageKey orders the results by the storage_key field.
func ByStorageKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStorageKey, opts...).ToFunc()
}

// ByMediaType orders the results by the media_type field.
func ByMediaType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMediaType, opts...).ToFunc()
}

// BySizeBytes orders the results by the size_bytes field.
func BySizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSizeBytes, opts...).ToFunc()
}

// ByDeleteAfter orders the results by the delete_after field.
func ByDeleteAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteAfter, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// ByDeleteReason orders the results by the delete_reason field.
func ByDeleteReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteReason, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByMessageField orders the results by message field.
func ByMessageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessageStep(), sql.OrderByField(field, opts...))
	}
}

// ByUploaderField orders the results by uploader field.
func ByUploaderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUploaderStep(), sql.OrderByField(field, opts...))
	}
}

// ByDeletedByUserField orders the results by deleted_by_user field.
func ByDeletedByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeletedByUserStep(), sql.OrderByField(field, opts...))
	}
}
func newMessageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessageInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MessageTable, MessageColumn),
	)
}
func newUploaderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UploaderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UploaderTable, UploaderColumn),
	)
}
func newDeletedByUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeletedByUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DeletedByUserTable, DeletedByUserColumn),
	)
}
