// Code generated by ent, DO NOT EDIT.

package videotask

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the videotask type in the database.
	Label = "video_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUpstreamTaskID holds the string denoting the upstream_task_id field in the database.
	FieldUpstreamTaskID = "upstream_task_id"
	// FieldBillingRequestID holds the string denoting the billing_request_id field in the database.
	FieldBillingRequestID = "billing_request_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldRefundAmount holds the string denoting the refund_amount field in the database.
	FieldRefundAmount = "refund_amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNextPollAt holds the string denoting the next_poll_at field in the database.
	FieldNextPollAt = "next_poll_at"
	// FieldLockedUntil holds the string denoting the locked_until field in the database.
	FieldLockedUntil = "locked_until"
	// FieldPollAttempts holds the string denoting the poll_attempts field in the database.
	FieldPollAttempts = "poll_attempts"
	// FieldTerminalAt holds the string denoting the terminal_at field in the database.
	FieldTerminalAt = "terminal_at"
	// FieldRefundedAt holds the string denoting the refunded_at field in the database.
	FieldRefundedAt = "refunded_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the videotask in the database.
	Table = "video_tasks"
)

// Columns holds all SQL columns for videotask fields.
var Columns = []string{
	FieldID,
	FieldUpstreamTaskID,
	FieldBillingRequestID,
	FieldUserID,
	FieldAPIKeyID,
	FieldAccountID,
	FieldGroupID,
	FieldRefundAmount,
	FieldStatus,
	FieldNextPollAt,
	FieldLockedUntil,
	FieldPollAttempts,
	FieldTerminalAt,
	FieldRefundedAt,
	FieldLastError,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UpstreamTaskIDValidator is a validator for the "upstream_task_id" field. It is called by the builders before save.
	UpstreamTaskIDValidator func(string) error
	// BillingRequestIDValidator is a validator for the "billing_request_id" field. It is called by the builders before save.
	BillingRequestIDValidator func(string) error
	// DefaultRefundAmount holds the default value on creation for the "refund_amount" field.
	DefaultRefundAmount float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultNextPollAt holds the default value on creation for the "next_poll_at" field.
	DefaultNextPollAt func() time.Time
	// DefaultPollAttempts holds the default value on creation for the "poll_attempts" field.
	DefaultPollAttempts int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the VideoTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUpstreamTaskID orders the results by the upstream_task_id field.
func ByUpstreamTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamTaskID, opts...).ToFunc()
}

// ByBillingRequestID orders the results by the billing_request_id field.
func ByBillingRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingRequestID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByRefundAmount orders the results by the refund_amount field.
func ByRefundAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNextPollAt orders the results by the next_poll_at field.
func ByNextPollAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextPollAt, opts...).ToFunc()
}

// ByLockedUntil orders the results by the locked_until field.
func ByLockedUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLockedUntil, opts...).ToFunc()
}

// ByPollAttempts orders the results by the poll_attempts field.
func ByPollAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPollAttempts, opts...).ToFunc()
}

// ByTerminalAt orders the results by the terminal_at field.
func ByTerminalAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTerminalAt, opts...).ToFunc()
}

// ByRefundedAt orders the results by the refunded_at field.
func ByRefundedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundedAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
