// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/playgroundconversation"
)

// PlaygroundConversationCreate is the builder for creating a PlaygroundConversation entity.
type PlaygroundConversationCreate struct {
	config
	mutation *PlaygroundConversationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlaygroundConversationCreate) SetCreatedAt(v time.Time) *PlaygroundConversationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlaygroundConversationCreate) SetNillableCreatedAt(v *time.Time) *PlaygroundConversationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlaygroundConversationCreate) SetUpdatedAt(v time.Time) *PlaygroundConversationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlaygroundConversationCreate) SetNillableUpdatedAt(v *time.Time) *PlaygroundConversationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PlaygroundConversationCreate) SetUserID(v int64) *PlaygroundConversationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *PlaygroundConversationCreate) SetTitle(v string) *PlaygroundConversationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *PlaygroundConversationCreate) SetNillableTitle(v *string) *PlaygroundConversationCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *PlaygroundConversationCreate) SetModel(v string) *PlaygroundConversationCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *PlaygroundConversationCreate) SetNillableModel(v *string) *PlaygroundConversationCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetGroupName sets the "group_name" field.
func (_c *PlaygroundConversationCreate) SetGroupName(v string) *PlaygroundConversationCreate {
	_c.mutation.SetGroupName(v)
	return _c
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_c *PlaygroundConversationCreate) SetNillableGroupName(v *string) *PlaygroundConversationCreate {
	if v != nil {
		_c.SetGroupName(*v)
	}
	return _c
}

// SetMessages sets the "messages" field.
func (_c *PlaygroundConversationCreate) SetMessages(v json.RawMessage) *PlaygroundConversationCreate {
	_c.mutation.SetMessages(v)
	return _c
}

// SetLastActivityAt sets the "last_activity_at" field.
func (_c *PlaygroundConversationCreate) SetLastActivityAt(v time.Time) *PlaygroundConversationCreate {
	_c.mutation.SetLastActivityAt(v)
	return _c
}

// SetNillableLastActivityAt sets the "last_activity_at" field if the given value is not nil.
func (_c *PlaygroundConversationCreate) SetNillableLastActivityAt(v *time.Time) *PlaygroundConversationCreate {
	if v != nil {
		_c.SetLastActivityAt(*v)
	}
	return _c
}

// Mutation returns the PlaygroundConversationMutation object of the builder.
func (_c *PlaygroundConversationCreate) Mutation() *PlaygroundConversationMutation {
	return _c.mutation
}

// Save creates the PlaygroundConversation in the database.
func (_c *PlaygroundConversationCreate) Save(ctx context.Context) (*PlaygroundConversation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlaygroundConversationCreate) SaveX(ctx context.Context) *PlaygroundConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlaygroundConversationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlaygroundConversationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlaygroundConversationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := playgroundconversation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := playgroundconversation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := playgroundconversation.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.LastActivityAt(); !ok {
		v := playgroundconversation.DefaultLastActivityAt()
		_c.mutation.SetLastActivityAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlaygroundConversationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PlaygroundConversation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PlaygroundConversation.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PlaygroundConversation.user_id"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := playgroundconversation.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "PlaygroundConversation.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastActivityAt(); !ok {
		return &ValidationError{Name: "last_activity_at", err: errors.New(`ent: missing required field "PlaygroundConversation.last_activity_at"`)}
	}
	return nil
}

func (_c *PlaygroundConversationCreate) sqlSave(ctx context.Context) (*PlaygroundConversation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlaygroundConversationCreate) createSpec() (*PlaygroundConversation, *sqlgraph.CreateSpec) {
	var (
		_node = &PlaygroundConversation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(playgroundconversation.Table, sqlgraph.NewFieldSpec(playgroundconversation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(playgroundconversation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(playgroundconversation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(playgroundconversation.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(playgroundconversation.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(playgroundconversation.FieldModel, field.TypeString, value)
		_node.Model = &value
	}
	if value, ok := _c.mutation.GroupName(); ok {
		_spec.SetField(playgroundconversation.FieldGroupName, field.TypeString, value)
		_node.GroupName = &value
	}
	if value, ok := _c.mutation.Messages(); ok {
		_spec.SetField(playgroundconversation.FieldMessages, field.TypeJSON, value)
		_node.Messages = value
	}
	if value, ok := _c.mutation.LastActivityAt(); ok {
		_spec.SetField(playgroundconversation.FieldLastActivityAt, field.TypeTime, value)
		_node.LastActivityAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PlaygroundConversation.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlaygroundConversationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PlaygroundConversationCreate) OnConflict(opts ...sql.ConflictOption) *PlaygroundConversationUpsertOne {
	_c.conflict = opts
	return &PlaygroundConversationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PlaygroundConversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlaygroundConversationCreate) OnConflictColumns(columns ...string) *PlaygroundConversationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlaygroundConversationUpsertOne{
		create: _c,
	}
}

type (
	// PlaygroundConversationUpsertOne is the builder for "upsert"-ing
	//  one PlaygroundConversation node.
	PlaygroundConversationUpsertOne struct {
		create *PlaygroundConversationCreate
	}

	// PlaygroundConversationUpsert is the "OnConflict" setter.
	PlaygroundConversationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PlaygroundConversationUpsert) SetUpdatedAt(v time.Time) *PlaygroundConversationUpsert {
	u.Set(playgroundconversation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlaygroundConversationUpsert) UpdateUpdatedAt() *PlaygroundConversationUpsert {
	u.SetExcluded(playgroundconversation.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *PlaygroundConversationUpsert) SetUserID(v int64) *PlaygroundConversationUpsert {
	u.Set(playgroundconversation.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PlaygroundConversationUpsert) UpdateUserID() *PlaygroundConversationUpsert {
	u.SetExcluded(playgroundconversation.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *PlaygroundConversationUpsert) AddUserID(v int64) *PlaygroundConversationUpsert {
	u.Add(playgroundconversation.FieldUserID, v)
	return u
}

// SetTitle sets the "title" field.
func (u *PlaygroundConversationUpsert) SetTitle(v string) *PlaygroundConversationUpsert {
	u.Set(playgroundconversation.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PlaygroundConversationUpsert) UpdateTitle() *PlaygroundConversationUpsert {
	u.SetExcluded(playgroundconversation.FieldTitle)
	return u
}

// ClearTitle clears the value of the "title" field.
func (u *PlaygroundConversationUpsert) ClearTitle() *PlaygroundConversationUpsert {
	u.SetNull(playgroundconversation.FieldTitle)
	return u
}

// SetModel sets the "model" field.
func (u *PlaygroundConversationUpsert) SetModel(v string) *PlaygroundConversationUpsert {
	u.Set(playgroundconversation.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *PlaygroundConversationUpsert) UpdateModel() *PlaygroundConversationUpsert {
	u.SetExcluded(playgroundconversation.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *PlaygroundConversationUpsert) ClearModel() *PlaygroundConversationUpsert {
	u.SetNull(playgroundconversation.FieldModel)
	return u
}

// SetGroupName sets the "group_name" field.
func (u *PlaygroundConversationUpsert) SetGroupName(v string) *PlaygroundConversationUpsert {
	u.Set(playgroundconversation.FieldGroupName, v)
	return u
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *PlaygroundConversationUpsert) UpdateGroupName() *PlaygroundConversationUpsert {
	u.SetExcluded(playgroundconversation.FieldGroupName)
	return u
}

// ClearGroupName clears the value of the "group_name" field.
func (u *PlaygroundConversationUpsert) ClearGroupName() *PlaygroundConversationUpsert {
	u.SetNull(playgroundconversation.FieldGroupName)
	return u
}

// SetMessages sets the "messages" field.
func (u *PlaygroundConversationUpsert) SetMessages(v json.RawMessage) *PlaygroundConversationUpsert {
	u.Set(playgroundconversation.FieldMessages, v)
	return u
}

// UpdateMessages sets the "messages" field to the value that was provided on create.
func (u *PlaygroundConversationUpsert) UpdateMessages() *PlaygroundConversationUpsert {
	u.SetExcluded(playgroundconversation.FieldMessages)
	return u
}

// ClearMessages clears the value of the "messages" field.
func (u *PlaygroundConversationUpsert) ClearMessages() *PlaygroundConversationUpsert {
	u.SetNull(playgroundconversation.FieldMessages)
	return u
}

// SetLastActivityAt sets the "last_activity_at" field.
func (u *PlaygroundConversationUpsert) SetLastActivityAt(v time.Time) *PlaygroundConversationUpsert {
	u.Set(playgroundconversation.FieldLastActivityAt, v)
	return u
}

// UpdateLastActivityAt sets the "last_activity_at" field to the value that was provided on create.
func (u *PlaygroundConversationUpsert) UpdateLastActivityAt() *PlaygroundConversationUpsert {
	u.SetExcluded(playgroundconversation.FieldLastActivityAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PlaygroundConversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PlaygroundConversationUpsertOne) UpdateNewValues() *PlaygroundConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(playgroundconversation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PlaygroundConversation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PlaygroundConversationUpsertOne) Ignore() *PlaygroundConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlaygroundConversationUpsertOne) DoNothing() *PlaygroundConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlaygroundConversationCreate.OnConflict
// documentation for more info.
func (u *PlaygroundConversationUpsertOne) Update(set func(*PlaygroundConversationUpsert)) *PlaygroundConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlaygroundConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlaygroundConversationUpsertOne) SetUpdatedAt(v time.Time) *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlaygroundConversationUpsertOne) UpdateUpdatedAt() *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *PlaygroundConversationUpsertOne) SetUserID(v int64) *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *PlaygroundConversationUpsertOne) AddUserID(v int64) *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PlaygroundConversationUpsertOne) UpdateUserID() *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.UpdateUserID()
	})
}

// SetTitle sets the "title" field.
func (u *PlaygroundConversationUpsertOne) SetTitle(v string) *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PlaygroundConversationUpsertOne) UpdateTitle() *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *PlaygroundConversationUpsertOne) ClearTitle() *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.ClearTitle()
	})
}

// SetModel sets the "model" field.
func (u *PlaygroundConversationUpsertOne) SetModel(v string) *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *PlaygroundConversationUpsertOne) UpdateModel() *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *PlaygroundConversationUpsertOne) ClearModel() *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.ClearModel()
	})
}

// SetGroupName sets the "group_name" field.
func (u *PlaygroundConversationUpsertOne) SetGroupName(v string) *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *PlaygroundConversationUpsertOne) UpdateGroupName() *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.UpdateGroupName()
	})
}

// ClearGroupName clears the value of the "group_name" field.
func (u *PlaygroundConversationUpsertOne) ClearGroupName() *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.ClearGroupName()
	})
}

// SetMessages sets the "messages" field.
func (u *PlaygroundConversationUpsertOne) SetMessages(v json.RawMessage) *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.SetMessages(v)
	})
}

// UpdateMessages sets the "messages" field to the value that was provided on create.
func (u *PlaygroundConversationUpsertOne) UpdateMessages() *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.UpdateMessages()
	})
}

// ClearMessages clears the value of the "messages" field.
func (u *PlaygroundConversationUpsertOne) ClearMessages() *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.ClearMessages()
	})
}

// SetLastActivityAt sets the "last_activity_at" field.
func (u *PlaygroundConversationUpsertOne) SetLastActivityAt(v time.Time) *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.SetLastActivityAt(v)
	})
}

// UpdateLastActivityAt sets the "last_activity_at" field to the value that was provided on create.
func (u *PlaygroundConversationUpsertOne) UpdateLastActivityAt() *PlaygroundConversationUpsertOne {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.UpdateLastActivityAt()
	})
}

// Exec executes the query.
func (u *PlaygroundConversationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlaygroundConversationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlaygroundConversationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PlaygroundConversationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PlaygroundConversationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PlaygroundConversationCreateBulk is the builder for creating many PlaygroundConversation entities in bulk.
type PlaygroundConversationCreateBulk struct {
	config
	err      error
	builders []*PlaygroundConversationCreate
	conflict []sql.ConflictOption
}

// Save creates the PlaygroundConversation entities in the database.
func (_c *PlaygroundConversationCreateBulk) Save(ctx context.Context) ([]*PlaygroundConversation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PlaygroundConversation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlaygroundConversationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlaygroundConversationCreateBulk) SaveX(ctx context.Context) []*PlaygroundConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlaygroundConversationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlaygroundConversationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PlaygroundConversation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlaygroundConversationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PlaygroundConversationCreateBulk) OnConflict(opts ...sql.ConflictOption) *PlaygroundConversationUpsertBulk {
	_c.conflict = opts
	return &PlaygroundConversationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PlaygroundConversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlaygroundConversationCreateBulk) OnConflictColumns(columns ...string) *PlaygroundConversationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlaygroundConversationUpsertBulk{
		create: _c,
	}
}

// PlaygroundConversationUpsertBulk is the builder for "upsert"-ing
// a bulk of PlaygroundConversation nodes.
type PlaygroundConversationUpsertBulk struct {
	create *PlaygroundConversationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PlaygroundConversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PlaygroundConversationUpsertBulk) UpdateNewValues() *PlaygroundConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(playgroundconversation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PlaygroundConversation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PlaygroundConversationUpsertBulk) Ignore() *PlaygroundConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlaygroundConversationUpsertBulk) DoNothing() *PlaygroundConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlaygroundConversationCreateBulk.OnConflict
// documentation for more info.
func (u *PlaygroundConversationUpsertBulk) Update(set func(*PlaygroundConversationUpsert)) *PlaygroundConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlaygroundConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlaygroundConversationUpsertBulk) SetUpdatedAt(v time.Time) *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlaygroundConversationUpsertBulk) UpdateUpdatedAt() *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *PlaygroundConversationUpsertBulk) SetUserID(v int64) *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *PlaygroundConversationUpsertBulk) AddUserID(v int64) *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PlaygroundConversationUpsertBulk) UpdateUserID() *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.UpdateUserID()
	})
}

// SetTitle sets the "title" field.
func (u *PlaygroundConversationUpsertBulk) SetTitle(v string) *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PlaygroundConversationUpsertBulk) UpdateTitle() *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *PlaygroundConversationUpsertBulk) ClearTitle() *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.ClearTitle()
	})
}

// SetModel sets the "model" field.
func (u *PlaygroundConversationUpsertBulk) SetModel(v string) *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *PlaygroundConversationUpsertBulk) UpdateModel() *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *PlaygroundConversationUpsertBulk) ClearModel() *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.ClearModel()
	})
}

// SetGroupName sets the "group_name" field.
func (u *PlaygroundConversationUpsertBulk) SetGroupName(v string) *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *PlaygroundConversationUpsertBulk) UpdateGroupName() *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.UpdateGroupName()
	})
}

// ClearGroupName clears the value of the "group_name" field.
func (u *PlaygroundConversationUpsertBulk) ClearGroupName() *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.ClearGroupName()
	})
}

// SetMessages sets the "messages" field.
func (u *PlaygroundConversationUpsertBulk) SetMessages(v json.RawMessage) *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.SetMessages(v)
	})
}

// UpdateMessages sets the "messages" field to the value that was provided on create.
func (u *PlaygroundConversationUpsertBulk) UpdateMessages() *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.UpdateMessages()
	})
}

// ClearMessages clears the value of the "messages" field.
func (u *PlaygroundConversationUpsertBulk) ClearMessages() *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.ClearMessages()
	})
}

// SetLastActivityAt sets the "last_activity_at" field.
func (u *PlaygroundConversationUpsertBulk) SetLastActivityAt(v time.Time) *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.SetLastActivityAt(v)
	})
}

// UpdateLastActivityAt sets the "last_activity_at" field to the value that was provided on create.
func (u *PlaygroundConversationUpsertBulk) UpdateLastActivityAt() *PlaygroundConversationUpsertBulk {
	return u.Update(func(s *PlaygroundConversationUpsert) {
		s.UpdateLastActivityAt()
	})
}

// Exec executes the query.
func (u *PlaygroundConversationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PlaygroundConversationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlaygroundConversationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlaygroundConversationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
