// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/playgroundconversation"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PlaygroundConversationDelete is the builder for deleting a PlaygroundConversation entity.
type PlaygroundConversationDelete struct {
	config
	hooks    []Hook
	mutation *PlaygroundConversationMutation
}

// Where appends a list predicates to the PlaygroundConversationDelete builder.
func (_d *PlaygroundConversationDelete) Where(ps ...predicate.PlaygroundConversation) *PlaygroundConversationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PlaygroundConversationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PlaygroundConversationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PlaygroundConversationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(playgroundconversation.Table, sqlgraph.NewFieldSpec(playgroundconversation.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PlaygroundConversationDeleteOne is the builder for deleting a single PlaygroundConversation entity.
type PlaygroundConversationDeleteOne struct {
	_d *PlaygroundConversationDelete
}

// Where appends a list predicates to the PlaygroundConversationDelete builder.
func (_d *PlaygroundConversationDeleteOne) Where(ps ...predicate.PlaygroundConversation) *PlaygroundConversationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PlaygroundConversationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{playgroundconversation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PlaygroundConversationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
