// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/playgroundconversation"
)

// PlaygroundConversation is the model entity for the PlaygroundConversation schema.
type PlaygroundConversation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 会话所属用户 ID
	UserID int64 `json:"user_id,omitempty"`
	// 会话标题（默认取首条消息前 20 字）
	Title string `json:"title,omitempty"`
	// 最后使用的模型标识（如 claude-3-5-sonnet）
	Model *string `json:"model,omitempty"`
	// 所属分组名称（可选，前端分类展示用）
	GroupName *string `json:"group_name,omitempty"`
	// 消息列表（JSONB 整存，后端透明存储不解析）
	Messages json.RawMessage `json:"messages,omitempty"`
	// 最后活动时间（保存消息时刷新，用于过期清理与列表排序）
	LastActivityAt time.Time `json:"last_activity_at,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlaygroundConversation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case playgroundconversation.FieldMessages:
			values[i] = new([]byte)
		case playgroundconversation.FieldID, playgroundconversation.FieldUserID:
			values[i] = new(sql.NullInt64)
		case playgroundconversation.FieldTitle, playgroundconversation.FieldModel, playgroundconversation.FieldGroupName:
			values[i] = new(sql.NullString)
		case playgroundconversation.FieldCreatedAt, playgroundconversation.FieldUpdatedAt, playgroundconversation.FieldLastActivityAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlaygroundConversation fields.
func (_m *PlaygroundConversation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case playgroundconversation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case playgroundconversation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case playgroundconversation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case playgroundconversation.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case playgroundconversation.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case playgroundconversation.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = new(string)
				*_m.Model = value.String
			}
		case playgroundconversation.FieldGroupName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_name", values[i])
			} else if value.Valid {
				_m.GroupName = new(string)
				*_m.GroupName = value.String
			}
		case playgroundconversation.FieldMessages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field messages", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Messages); err != nil {
					return fmt.Errorf("unmarshal field messages: %w", err)
				}
			}
		case playgroundconversation.FieldLastActivityAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_activity_at", values[i])
			} else if value.Valid {
				_m.LastActivityAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlaygroundConversation.
// This includes values selected through modifiers, order, etc.
func (_m *PlaygroundConversation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PlaygroundConversation.
// Note that you need to call PlaygroundConversation.Unwrap() before calling this method if this PlaygroundConversation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlaygroundConversation) Update() *PlaygroundConversationUpdateOne {
	return NewPlaygroundConversationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlaygroundConversation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlaygroundConversation) Unwrap() *PlaygroundConversation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlaygroundConversation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlaygroundConversation) String() string {
	var builder strings.Builder
	builder.WriteString("PlaygroundConversation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.Model; v != nil {
		builder.WriteString("model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GroupName; v != nil {
		builder.WriteString("group_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("messages=")
	builder.WriteString(fmt.Sprintf("%v", _m.Messages))
	builder.WriteString(", ")
	builder.WriteString("last_activity_at=")
	builder.WriteString(_m.LastActivityAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PlaygroundConversations is a parsable slice of PlaygroundConversation.
type PlaygroundConversations []*PlaygroundConversation
