// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionrequestreservation"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionRequestReservation is the model entity for the SubscriptionRequestReservation schema.
type SubscriptionRequestReservation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID int64 `json:"subscription_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Window5hStart holds the value of the "window_5h_start" field.
	Window5hStart *time.Time `json:"window_5h_start,omitempty"`
	// Window1dStart holds the value of the "window_1d_start" field.
	Window1dStart *time.Time `json:"window_1d_start,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionRequestReservationQuery when eager-loading is set.
	Edges        SubscriptionRequestReservationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionRequestReservationEdges holds the relations/edges for other nodes in the graph.
type SubscriptionRequestReservationEdges struct {
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Subscription holds the value of the subscription edge.
	Subscription *UserSubscription `json:"subscription,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionRequestReservationEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionRequestReservationEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionRequestReservationEdges) SubscriptionOrErr() (*UserSubscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionRequestReservation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionrequestreservation.FieldID, subscriptionrequestreservation.FieldAPIKeyID, subscriptionrequestreservation.FieldUserID, subscriptionrequestreservation.FieldSubscriptionID:
			values[i] = new(sql.NullInt64)
		case subscriptionrequestreservation.FieldRequestID, subscriptionrequestreservation.FieldStatus:
			values[i] = new(sql.NullString)
		case subscriptionrequestreservation.FieldWindow5hStart, subscriptionrequestreservation.FieldWindow1dStart, subscriptionrequestreservation.FieldExpiresAt, subscriptionrequestreservation.FieldCreatedAt, subscriptionrequestreservation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionRequestReservation fields.
func (_m *SubscriptionRequestReservation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionrequestreservation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionrequestreservation.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case subscriptionrequestreservation.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case subscriptionrequestreservation.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case subscriptionrequestreservation.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = value.Int64
			}
		case subscriptionrequestreservation.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case subscriptionrequestreservation.FieldWindow5hStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_5h_start", values[i])
			} else if value.Valid {
				_m.Window5hStart = new(time.Time)
				*_m.Window5hStart = value.Time
			}
		case subscriptionrequestreservation.FieldWindow1dStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_1d_start", values[i])
			} else if value.Valid {
				_m.Window1dStart = new(time.Time)
				*_m.Window1dStart = value.Time
			}
		case subscriptionrequestreservation.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case subscriptionrequestreservation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionrequestreservation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionRequestReservation.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionRequestReservation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAPIKey queries the "api_key" edge of the SubscriptionRequestReservation entity.
func (_m *SubscriptionRequestReservation) QueryAPIKey() *APIKeyQuery {
	return NewSubscriptionRequestReservationClient(_m.config).QueryAPIKey(_m)
}

// QueryUser queries the "user" edge of the SubscriptionRequestReservation entity.
func (_m *SubscriptionRequestReservation) QueryUser() *UserQuery {
	return NewSubscriptionRequestReservationClient(_m.config).QueryUser(_m)
}

// QuerySubscription queries the "subscription" edge of the SubscriptionRequestReservation entity.
func (_m *SubscriptionRequestReservation) QuerySubscription() *UserSubscriptionQuery {
	return NewSubscriptionRequestReservationClient(_m.config).QuerySubscription(_m)
}

// Update returns a builder for updating this SubscriptionRequestReservation.
// Note that you need to call SubscriptionRequestReservation.Unwrap() before calling this method if this SubscriptionRequestReservation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionRequestReservation) Update() *SubscriptionRequestReservationUpdateOne {
	return NewSubscriptionRequestReservationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionRequestReservation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionRequestReservation) Unwrap() *SubscriptionRequestReservation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionRequestReservation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionRequestReservation) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionRequestReservation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("subscription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.Window5hStart; v != nil {
		builder.WriteString("window_5h_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Window1dStart; v != nil {
		builder.WriteString("window_1d_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionRequestReservations is a parsable slice of SubscriptionRequestReservation.
type SubscriptionRequestReservations []*SubscriptionRequestReservation
