// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionrequestreservation"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionRequestReservationUpdate is the builder for updating SubscriptionRequestReservation entities.
type SubscriptionRequestReservationUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionRequestReservationMutation
}

// Where appends a list predicates to the SubscriptionRequestReservationUpdate builder.
func (_u *SubscriptionRequestReservationUpdate) Where(ps ...predicate.SubscriptionRequestReservation) *SubscriptionRequestReservationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *SubscriptionRequestReservationUpdate) SetRequestID(v string) *SubscriptionRequestReservationUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdate) SetNillableRequestID(v *string) *SubscriptionRequestReservationUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *SubscriptionRequestReservationUpdate) SetAPIKeyID(v int64) *SubscriptionRequestReservationUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdate) SetNillableAPIKeyID(v *int64) *SubscriptionRequestReservationUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionRequestReservationUpdate) SetUserID(v int64) *SubscriptionRequestReservationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdate) SetNillableUserID(v *int64) *SubscriptionRequestReservationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionRequestReservationUpdate) SetSubscriptionID(v int64) *SubscriptionRequestReservationUpdate {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdate) SetNillableSubscriptionID(v *int64) *SubscriptionRequestReservationUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionRequestReservationUpdate) SetStatus(v string) *SubscriptionRequestReservationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdate) SetNillableStatus(v *string) *SubscriptionRequestReservationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetWindow5hStart sets the "window_5h_start" field.
func (_u *SubscriptionRequestReservationUpdate) SetWindow5hStart(v time.Time) *SubscriptionRequestReservationUpdate {
	_u.mutation.SetWindow5hStart(v)
	return _u
}

// SetNillableWindow5hStart sets the "window_5h_start" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdate) SetNillableWindow5hStart(v *time.Time) *SubscriptionRequestReservationUpdate {
	if v != nil {
		_u.SetWindow5hStart(*v)
	}
	return _u
}

// ClearWindow5hStart clears the value of the "window_5h_start" field.
func (_u *SubscriptionRequestReservationUpdate) ClearWindow5hStart() *SubscriptionRequestReservationUpdate {
	_u.mutation.ClearWindow5hStart()
	return _u
}

// SetWindow1dStart sets the "window_1d_start" field.
func (_u *SubscriptionRequestReservationUpdate) SetWindow1dStart(v time.Time) *SubscriptionRequestReservationUpdate {
	_u.mutation.SetWindow1dStart(v)
	return _u
}

// SetNillableWindow1dStart sets the "window_1d_start" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdate) SetNillableWindow1dStart(v *time.Time) *SubscriptionRequestReservationUpdate {
	if v != nil {
		_u.SetWindow1dStart(*v)
	}
	return _u
}

// ClearWindow1dStart clears the value of the "window_1d_start" field.
func (_u *SubscriptionRequestReservationUpdate) ClearWindow1dStart() *SubscriptionRequestReservationUpdate {
	_u.mutation.ClearWindow1dStart()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionRequestReservationUpdate) SetExpiresAt(v time.Time) *SubscriptionRequestReservationUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdate) SetNillableExpiresAt(v *time.Time) *SubscriptionRequestReservationUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionRequestReservationUpdate) SetUpdatedAt(v time.Time) *SubscriptionRequestReservationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *SubscriptionRequestReservationUpdate) SetAPIKey(v *APIKey) *SubscriptionRequestReservationUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionRequestReservationUpdate) SetUser(v *User) *SubscriptionRequestReservationUpdate {
	return _u.SetUserID(v.ID)
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionRequestReservationUpdate) SetSubscription(v *UserSubscription) *SubscriptionRequestReservationUpdate {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionRequestReservationMutation object of the builder.
func (_u *SubscriptionRequestReservationUpdate) Mutation() *SubscriptionRequestReservationMutation {
	return _u.mutation
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *SubscriptionRequestReservationUpdate) ClearAPIKey() *SubscriptionRequestReservationUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionRequestReservationUpdate) ClearUser() *SubscriptionRequestReservationUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionRequestReservationUpdate) ClearSubscription() *SubscriptionRequestReservationUpdate {
	_u.mutation.ClearSubscription()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionRequestReservationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionRequestReservationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionRequestReservationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionRequestReservationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionRequestReservationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionrequestreservation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionRequestReservationUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := subscriptionrequestreservation.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionRequestReservation.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionrequestreservation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionRequestReservation.status": %w`, err)}
		}
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionRequestReservation.api_key"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionRequestReservation.user"`)
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionRequestReservation.subscription"`)
	}
	return nil
}

func (_u *SubscriptionRequestReservationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionrequestreservation.Table, subscriptionrequestreservation.Columns, sqlgraph.NewFieldSpec(subscriptionrequestreservation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(subscriptionrequestreservation.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionrequestreservation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Window5hStart(); ok {
		_spec.SetField(subscriptionrequestreservation.FieldWindow5hStart, field.TypeTime, value)
	}
	if _u.mutation.Window5hStartCleared() {
		_spec.ClearField(subscriptionrequestreservation.FieldWindow5hStart, field.TypeTime)
	}
	if value, ok := _u.mutation.Window1dStart(); ok {
		_spec.SetField(subscriptionrequestreservation.FieldWindow1dStart, field.TypeTime, value)
	}
	if _u.mutation.Window1dStartCleared() {
		_spec.ClearField(subscriptionrequestreservation.FieldWindow1dStart, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionrequestreservation.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionrequestreservation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrequestreservation.APIKeyTable,
			Columns: []string{subscriptionrequestreservation.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrequestreservation.APIKeyTable,
			Columns: []string{subscriptionrequestreservation.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrequestreservation.UserTable,
			Columns: []string{subscriptionrequestreservation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrequestreservation.UserTable,
			Columns: []string{subscriptionrequestreservation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrequestreservation.SubscriptionTable,
			Columns: []string{subscriptionrequestreservation.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrequestreservation.SubscriptionTable,
			Columns: []string{subscriptionrequestreservation.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionrequestreservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionRequestReservationUpdateOne is the builder for updating a single SubscriptionRequestReservation entity.
type SubscriptionRequestReservationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionRequestReservationMutation
}

// SetRequestID sets the "request_id" field.
func (_u *SubscriptionRequestReservationUpdateOne) SetRequestID(v string) *SubscriptionRequestReservationUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdateOne) SetNillableRequestID(v *string) *SubscriptionRequestReservationUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *SubscriptionRequestReservationUpdateOne) SetAPIKeyID(v int64) *SubscriptionRequestReservationUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdateOne) SetNillableAPIKeyID(v *int64) *SubscriptionRequestReservationUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionRequestReservationUpdateOne) SetUserID(v int64) *SubscriptionRequestReservationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdateOne) SetNillableUserID(v *int64) *SubscriptionRequestReservationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionRequestReservationUpdateOne) SetSubscriptionID(v int64) *SubscriptionRequestReservationUpdateOne {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdateOne) SetNillableSubscriptionID(v *int64) *SubscriptionRequestReservationUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionRequestReservationUpdateOne) SetStatus(v string) *SubscriptionRequestReservationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdateOne) SetNillableStatus(v *string) *SubscriptionRequestReservationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetWindow5hStart sets the "window_5h_start" field.
func (_u *SubscriptionRequestReservationUpdateOne) SetWindow5hStart(v time.Time) *SubscriptionRequestReservationUpdateOne {
	_u.mutation.SetWindow5hStart(v)
	return _u
}

// SetNillableWindow5hStart sets the "window_5h_start" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdateOne) SetNillableWindow5hStart(v *time.Time) *SubscriptionRequestReservationUpdateOne {
	if v != nil {
		_u.SetWindow5hStart(*v)
	}
	return _u
}

// ClearWindow5hStart clears the value of the "window_5h_start" field.
func (_u *SubscriptionRequestReservationUpdateOne) ClearWindow5hStart() *SubscriptionRequestReservationUpdateOne {
	_u.mutation.ClearWindow5hStart()
	return _u
}

// SetWindow1dStart sets the "window_1d_start" field.
func (_u *SubscriptionRequestReservationUpdateOne) SetWindow1dStart(v time.Time) *SubscriptionRequestReservationUpdateOne {
	_u.mutation.SetWindow1dStart(v)
	return _u
}

// SetNillableWindow1dStart sets the "window_1d_start" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdateOne) SetNillableWindow1dStart(v *time.Time) *SubscriptionRequestReservationUpdateOne {
	if v != nil {
		_u.SetWindow1dStart(*v)
	}
	return _u
}

// ClearWindow1dStart clears the value of the "window_1d_start" field.
func (_u *SubscriptionRequestReservationUpdateOne) ClearWindow1dStart() *SubscriptionRequestReservationUpdateOne {
	_u.mutation.ClearWindow1dStart()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionRequestReservationUpdateOne) SetExpiresAt(v time.Time) *SubscriptionRequestReservationUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionRequestReservationUpdateOne) SetNillableExpiresAt(v *time.Time) *SubscriptionRequestReservationUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionRequestReservationUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionRequestReservationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *SubscriptionRequestReservationUpdateOne) SetAPIKey(v *APIKey) *SubscriptionRequestReservationUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionRequestReservationUpdateOne) SetUser(v *User) *SubscriptionRequestReservationUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionRequestReservationUpdateOne) SetSubscription(v *UserSubscription) *SubscriptionRequestReservationUpdateOne {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionRequestReservationMutation object of the builder.
func (_u *SubscriptionRequestReservationUpdateOne) Mutation() *SubscriptionRequestReservationMutation {
	return _u.mutation
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *SubscriptionRequestReservationUpdateOne) ClearAPIKey() *SubscriptionRequestReservationUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionRequestReservationUpdateOne) ClearUser() *SubscriptionRequestReservationUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionRequestReservationUpdateOne) ClearSubscription() *SubscriptionRequestReservationUpdateOne {
	_u.mutation.ClearSubscription()
	return _u
}

// Where appends a list predicates to the SubscriptionRequestReservationUpdate builder.
func (_u *SubscriptionRequestReservationUpdateOne) Where(ps ...predicate.SubscriptionRequestReservation) *SubscriptionRequestReservationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionRequestReservationUpdateOne) Select(field string, fields ...string) *SubscriptionRequestReservationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionRequestReservation entity.
func (_u *SubscriptionRequestReservationUpdateOne) Save(ctx context.Context) (*SubscriptionRequestReservation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionRequestReservationUpdateOne) SaveX(ctx context.Context) *SubscriptionRequestReservation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionRequestReservationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionRequestReservationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionRequestReservationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionrequestreservation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionRequestReservationUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := subscriptionrequestreservation.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionRequestReservation.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionrequestreservation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionRequestReservation.status": %w`, err)}
		}
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionRequestReservation.api_key"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionRequestReservation.user"`)
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionRequestReservation.subscription"`)
	}
	return nil
}

func (_u *SubscriptionRequestReservationUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionRequestReservation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionrequestreservation.Table, subscriptionrequestreservation.Columns, sqlgraph.NewFieldSpec(subscriptionrequestreservation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionRequestReservation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionrequestreservation.FieldID)
		for _, f := range fields {
			if !subscriptionrequestreservation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionrequestreservation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(subscriptionrequestreservation.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionrequestreservation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Window5hStart(); ok {
		_spec.SetField(subscriptionrequestreservation.FieldWindow5hStart, field.TypeTime, value)
	}
	if _u.mutation.Window5hStartCleared() {
		_spec.ClearField(subscriptionrequestreservation.FieldWindow5hStart, field.TypeTime)
	}
	if value, ok := _u.mutation.Window1dStart(); ok {
		_spec.SetField(subscriptionrequestreservation.FieldWindow1dStart, field.TypeTime, value)
	}
	if _u.mutation.Window1dStartCleared() {
		_spec.ClearField(subscriptionrequestreservation.FieldWindow1dStart, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionrequestreservation.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionrequestreservation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrequestreservation.APIKeyTable,
			Columns: []string{subscriptionrequestreservation.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrequestreservation.APIKeyTable,
			Columns: []string{subscriptionrequestreservation.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrequestreservation.UserTable,
			Columns: []string{subscriptionrequestreservation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrequestreservation.UserTable,
			Columns: []string{subscriptionrequestreservation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrequestreservation.SubscriptionTable,
			Columns: []string{subscriptionrequestreservation.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrequestreservation.SubscriptionTable,
			Columns: []string{subscriptionrequestreservation.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionRequestReservation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionrequestreservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
