// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/supportticketattachment"
	"github.com/Wei-Shaw/sub2api/ent/supportticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportTicketAttachmentCreate is the builder for creating a SupportTicketAttachment entity.
type SupportTicketAttachmentCreate struct {
	config
	mutation *SupportTicketAttachmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMessageID sets the "message_id" field.
func (_c *SupportTicketAttachmentCreate) SetMessageID(v int64) *SupportTicketAttachmentCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetUploaderID sets the "uploader_id" field.
func (_c *SupportTicketAttachmentCreate) SetUploaderID(v int64) *SupportTicketAttachmentCreate {
	_c.mutation.SetUploaderID(v)
	return _c
}

// SetOriginalName sets the "original_name" field.
func (_c *SupportTicketAttachmentCreate) SetOriginalName(v string) *SupportTicketAttachmentCreate {
	_c.mutation.SetOriginalName(v)
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *SupportTicketAttachmentCreate) SetStorageKey(v string) *SupportTicketAttachmentCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetMediaType sets the "media_type" field.
func (_c *SupportTicketAttachmentCreate) SetMediaType(v string) *SupportTicketAttachmentCreate {
	_c.mutation.SetMediaType(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *SupportTicketAttachmentCreate) SetSizeBytes(v int64) *SupportTicketAttachmentCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetDeleteAfter sets the "delete_after" field.
func (_c *SupportTicketAttachmentCreate) SetDeleteAfter(v time.Time) *SupportTicketAttachmentCreate {
	_c.mutation.SetDeleteAfter(v)
	return _c
}

// SetNillableDeleteAfter sets the "delete_after" field if the given value is not nil.
func (_c *SupportTicketAttachmentCreate) SetNillableDeleteAfter(v *time.Time) *SupportTicketAttachmentCreate {
	if v != nil {
		_c.SetDeleteAfter(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SupportTicketAttachmentCreate) SetDeletedAt(v time.Time) *SupportTicketAttachmentCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SupportTicketAttachmentCreate) SetNillableDeletedAt(v *time.Time) *SupportTicketAttachmentCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *SupportTicketAttachmentCreate) SetDeletedBy(v int64) *SupportTicketAttachmentCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *SupportTicketAttachmentCreate) SetNillableDeletedBy(v *int64) *SupportTicketAttachmentCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetDeleteReason sets the "delete_reason" field.
func (_c *SupportTicketAttachmentCreate) SetDeleteReason(v string) *SupportTicketAttachmentCreate {
	_c.mutation.SetDeleteReason(v)
	return _c
}

// SetNillableDeleteReason sets the "delete_reason" field if the given value is not nil.
func (_c *SupportTicketAttachmentCreate) SetNillableDeleteReason(v *string) *SupportTicketAttachmentCreate {
	if v != nil {
		_c.SetDeleteReason(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SupportTicketAttachmentCreate) SetCreatedAt(v time.Time) *SupportTicketAttachmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SupportTicketAttachmentCreate) SetNillableCreatedAt(v *time.Time) *SupportTicketAttachmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetMessage sets the "message" edge to the SupportTicketMessage entity.
func (_c *SupportTicketAttachmentCreate) SetMessage(v *SupportTicketMessage) *SupportTicketAttachmentCreate {
	return _c.SetMessageID(v.ID)
}

// SetUploader sets the "uploader" edge to the User entity.
func (_c *SupportTicketAttachmentCreate) SetUploader(v *User) *SupportTicketAttachmentCreate {
	return _c.SetUploaderID(v.ID)
}

// SetDeletedByUserID sets the "deleted_by_user" edge to the User entity by ID.
func (_c *SupportTicketAttachmentCreate) SetDeletedByUserID(id int64) *SupportTicketAttachmentCreate {
	_c.mutation.SetDeletedByUserID(id)
	return _c
}

// SetNillableDeletedByUserID sets the "deleted_by_user" edge to the User entity by ID if the given value is not nil.
func (_c *SupportTicketAttachmentCreate) SetNillableDeletedByUserID(id *int64) *SupportTicketAttachmentCreate {
	if id != nil {
		_c = _c.SetDeletedByUserID(*id)
	}
	return _c
}

// SetDeletedByUser sets the "deleted_by_user" edge to the User entity.
func (_c *SupportTicketAttachmentCreate) SetDeletedByUser(v *User) *SupportTicketAttachmentCreate {
	return _c.SetDeletedByUserID(v.ID)
}

// Mutation returns the SupportTicketAttachmentMutation object of the builder.
func (_c *SupportTicketAttachmentCreate) Mutation() *SupportTicketAttachmentMutation {
	return _c.mutation
}

// Save creates the SupportTicketAttachment in the database.
func (_c *SupportTicketAttachmentCreate) Save(ctx context.Context) (*SupportTicketAttachment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupportTicketAttachmentCreate) SaveX(ctx context.Context) *SupportTicketAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportTicketAttachmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportTicketAttachmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupportTicketAttachmentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := supportticketattachment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupportTicketAttachmentCreate) check() error {
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "SupportTicketAttachment.message_id"`)}
	}
	if _, ok := _c.mutation.UploaderID(); !ok {
		return &ValidationError{Name: "uploader_id", err: errors.New(`ent: missing required field "SupportTicketAttachment.uploader_id"`)}
	}
	if _, ok := _c.mutation.OriginalName(); !ok {
		return &ValidationError{Name: "original_name", err: errors.New(`ent: missing required field "SupportTicketAttachment.original_name"`)}
	}
	if v, ok := _c.mutation.OriginalName(); ok {
		if err := supportticketattachment.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.original_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "SupportTicketAttachment.storage_key"`)}
	}
	if v, ok := _c.mutation.StorageKey(); ok {
		if err := supportticketattachment.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.storage_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MediaType(); !ok {
		return &ValidationError{Name: "media_type", err: errors.New(`ent: missing required field "SupportTicketAttachment.media_type"`)}
	}
	if v, ok := _c.mutation.MediaType(); ok {
		if err := supportticketattachment.MediaTypeValidator(v); err != nil {
			return &ValidationError{Name: "media_type", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.media_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "SupportTicketAttachment.size_bytes"`)}
	}
	if v, ok := _c.mutation.DeleteReason(); ok {
		if err := supportticketattachment.DeleteReasonValidator(v); err != nil {
			return &ValidationError{Name: "delete_reason", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.delete_reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SupportTicketAttachment.created_at"`)}
	}
	if len(_c.mutation.MessageIDs()) == 0 {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required edge "SupportTicketAttachment.message"`)}
	}
	if len(_c.mutation.UploaderIDs()) == 0 {
		return &ValidationError{Name: "uploader", err: errors.New(`ent: missing required edge "SupportTicketAttachment.uploader"`)}
	}
	return nil
}

func (_c *SupportTicketAttachmentCreate) sqlSave(ctx context.Context) (*SupportTicketAttachment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupportTicketAttachmentCreate) createSpec() (*SupportTicketAttachment, *sqlgraph.CreateSpec) {
	var (
		_node = &SupportTicketAttachment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supportticketattachment.Table, sqlgraph.NewFieldSpec(supportticketattachment.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OriginalName(); ok {
		_spec.SetField(supportticketattachment.FieldOriginalName, field.TypeString, value)
		_node.OriginalName = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(supportticketattachment.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.MediaType(); ok {
		_spec.SetField(supportticketattachment.FieldMediaType, field.TypeString, value)
		_node.MediaType = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(supportticketattachment.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.DeleteAfter(); ok {
		_spec.SetField(supportticketattachment.FieldDeleteAfter, field.TypeTime, value)
		_node.DeleteAfter = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(supportticketattachment.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.DeleteReason(); ok {
		_spec.SetField(supportticketattachment.FieldDeleteReason, field.TypeString, value)
		_node.DeleteReason = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(supportticketattachment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.MessageTable,
			Columns: []string{supportticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MessageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.UploaderTable,
			Columns: []string{supportticketattachment.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UploaderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeletedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.DeletedByUserTable,
			Columns: []string{supportticketattachment.DeletedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DeletedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportTicketAttachment.Create().
//		SetMessageID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportTicketAttachmentUpsert) {
//			SetMessageID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportTicketAttachmentCreate) OnConflict(opts ...sql.ConflictOption) *SupportTicketAttachmentUpsertOne {
	_c.conflict = opts
	return &SupportTicketAttachmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportTicketAttachmentCreate) OnConflictColumns(columns ...string) *SupportTicketAttachmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportTicketAttachmentUpsertOne{
		create: _c,
	}
}

type (
	// SupportTicketAttachmentUpsertOne is the builder for "upsert"-ing
	//  one SupportTicketAttachment node.
	SupportTicketAttachmentUpsertOne struct {
		create *SupportTicketAttachmentCreate
	}

	// SupportTicketAttachmentUpsert is the "OnConflict" setter.
	SupportTicketAttachmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetMessageID sets the "message_id" field.
func (u *SupportTicketAttachmentUpsert) SetMessageID(v int64) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldMessageID, v)
	return u
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateMessageID() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldMessageID)
	return u
}

// SetUploaderID sets the "uploader_id" field.
func (u *SupportTicketAttachmentUpsert) SetUploaderID(v int64) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldUploaderID, v)
	return u
}

// UpdateUploaderID sets the "uploader_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateUploaderID() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldUploaderID)
	return u
}

// SetOriginalName sets the "original_name" field.
func (u *SupportTicketAttachmentUpsert) SetOriginalName(v string) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldOriginalName, v)
	return u
}

// UpdateOriginalName sets the "original_name" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateOriginalName() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldOriginalName)
	return u
}

// SetStorageKey sets the "storage_key" field.
func (u *SupportTicketAttachmentUpsert) SetStorageKey(v string) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldStorageKey, v)
	return u
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateStorageKey() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldStorageKey)
	return u
}

// SetMediaType sets the "media_type" field.
func (u *SupportTicketAttachmentUpsert) SetMediaType(v string) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldMediaType, v)
	return u
}

// UpdateMediaType sets the "media_type" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateMediaType() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldMediaType)
	return u
}

// SetSizeBytes sets the "size_bytes" field.
func (u *SupportTicketAttachmentUpsert) SetSizeBytes(v int64) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldSizeBytes, v)
	return u
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateSizeBytes() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldSizeBytes)
	return u
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *SupportTicketAttachmentUpsert) AddSizeBytes(v int64) *SupportTicketAttachmentUpsert {
	u.Add(supportticketattachment.FieldSizeBytes, v)
	return u
}

// SetDeleteAfter sets the "delete_after" field.
func (u *SupportTicketAttachmentUpsert) SetDeleteAfter(v time.Time) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldDeleteAfter, v)
	return u
}

// UpdateDeleteAfter sets the "delete_after" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateDeleteAfter() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldDeleteAfter)
	return u
}

// ClearDeleteAfter clears the value of the "delete_after" field.
func (u *SupportTicketAttachmentUpsert) ClearDeleteAfter() *SupportTicketAttachmentUpsert {
	u.SetNull(supportticketattachment.FieldDeleteAfter)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SupportTicketAttachmentUpsert) SetDeletedAt(v time.Time) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateDeletedAt() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SupportTicketAttachmentUpsert) ClearDeletedAt() *SupportTicketAttachmentUpsert {
	u.SetNull(supportticketattachment.FieldDeletedAt)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *SupportTicketAttachmentUpsert) SetDeletedBy(v int64) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateDeletedBy() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldDeletedBy)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *SupportTicketAttachmentUpsert) ClearDeletedBy() *SupportTicketAttachmentUpsert {
	u.SetNull(supportticketattachment.FieldDeletedBy)
	return u
}

// SetDeleteReason sets the "delete_reason" field.
func (u *SupportTicketAttachmentUpsert) SetDeleteReason(v string) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldDeleteReason, v)
	return u
}

// UpdateDeleteReason sets the "delete_reason" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateDeleteReason() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldDeleteReason)
	return u
}

// ClearDeleteReason clears the value of the "delete_reason" field.
func (u *SupportTicketAttachmentUpsert) ClearDeleteReason() *SupportTicketAttachmentUpsert {
	u.SetNull(supportticketattachment.FieldDeleteReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportTicketAttachmentUpsertOne) UpdateNewValues() *SupportTicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(supportticketattachment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SupportTicketAttachmentUpsertOne) Ignore() *SupportTicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportTicketAttachmentUpsertOne) DoNothing() *SupportTicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportTicketAttachmentCreate.OnConflict
// documentation for more info.
func (u *SupportTicketAttachmentUpsertOne) Update(set func(*SupportTicketAttachmentUpsert)) *SupportTicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportTicketAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetMessageID sets the "message_id" field.
func (u *SupportTicketAttachmentUpsertOne) SetMessageID(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateMessageID() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateMessageID()
	})
}

// SetUploaderID sets the "uploader_id" field.
func (u *SupportTicketAttachmentUpsertOne) SetUploaderID(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetUploaderID(v)
	})
}

// UpdateUploaderID sets the "uploader_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateUploaderID() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateUploaderID()
	})
}

// SetOriginalName sets the "original_name" field.
func (u *SupportTicketAttachmentUpsertOne) SetOriginalName(v string) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetOriginalName(v)
	})
}

// UpdateOriginalName sets the "original_name" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateOriginalName() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateOriginalName()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *SupportTicketAttachmentUpsertOne) SetStorageKey(v string) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateStorageKey() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateStorageKey()
	})
}

// SetMediaType sets the "media_type" field.
func (u *SupportTicketAttachmentUpsertOne) SetMediaType(v string) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetMediaType(v)
	})
}

// UpdateMediaType sets the "media_type" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateMediaType() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateMediaType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *SupportTicketAttachmentUpsertOne) SetSizeBytes(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *SupportTicketAttachmentUpsertOne) AddSizeBytes(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateSizeBytes() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetDeleteAfter sets the "delete_after" field.
func (u *SupportTicketAttachmentUpsertOne) SetDeleteAfter(v time.Time) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetDeleteAfter(v)
	})
}

// UpdateDeleteAfter sets the "delete_after" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateDeleteAfter() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateDeleteAfter()
	})
}

// ClearDeleteAfter clears the value of the "delete_after" field.
func (u *SupportTicketAttachmentUpsertOne) ClearDeleteAfter() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearDeleteAfter()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SupportTicketAttachmentUpsertOne) SetDeletedAt(v time.Time) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateDeletedAt() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SupportTicketAttachmentUpsertOne) ClearDeletedAt() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *SupportTicketAttachmentUpsertOne) SetDeletedBy(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateDeletedBy() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *SupportTicketAttachmentUpsertOne) ClearDeletedBy() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearDeletedBy()
	})
}

// SetDeleteReason sets the "delete_reason" field.
func (u *SupportTicketAttachmentUpsertOne) SetDeleteReason(v string) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetDeleteReason(v)
	})
}

// UpdateDeleteReason sets the "delete_reason" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateDeleteReason() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateDeleteReason()
	})
}

// ClearDeleteReason clears the value of the "delete_reason" field.
func (u *SupportTicketAttachmentUpsertOne) ClearDeleteReason() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearDeleteReason()
	})
}

// Exec executes the query.
func (u *SupportTicketAttachmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportTicketAttachmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportTicketAttachmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SupportTicketAttachmentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SupportTicketAttachmentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SupportTicketAttachmentCreateBulk is the builder for creating many SupportTicketAttachment entities in bulk.
type SupportTicketAttachmentCreateBulk struct {
	config
	err      error
	builders []*SupportTicketAttachmentCreate
	conflict []sql.ConflictOption
}

// Save creates the SupportTicketAttachment entities in the database.
func (_c *SupportTicketAttachmentCreateBulk) Save(ctx context.Context) ([]*SupportTicketAttachment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SupportTicketAttachment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupportTicketAttachmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupportTicketAttachmentCreateBulk) SaveX(ctx context.Context) []*SupportTicketAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportTicketAttachmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportTicketAttachmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportTicketAttachment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportTicketAttachmentUpsert) {
//			SetMessageID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportTicketAttachmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *SupportTicketAttachmentUpsertBulk {
	_c.conflict = opts
	return &SupportTicketAttachmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportTicketAttachmentCreateBulk) OnConflictColumns(columns ...string) *SupportTicketAttachmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportTicketAttachmentUpsertBulk{
		create: _c,
	}
}

// SupportTicketAttachmentUpsertBulk is the builder for "upsert"-ing
// a bulk of SupportTicketAttachment nodes.
type SupportTicketAttachmentUpsertBulk struct {
	create *SupportTicketAttachmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportTicketAttachmentUpsertBulk) UpdateNewValues() *SupportTicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(supportticketattachment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SupportTicketAttachmentUpsertBulk) Ignore() *SupportTicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportTicketAttachmentUpsertBulk) DoNothing() *SupportTicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportTicketAttachmentCreateBulk.OnConflict
// documentation for more info.
func (u *SupportTicketAttachmentUpsertBulk) Update(set func(*SupportTicketAttachmentUpsert)) *SupportTicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportTicketAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetMessageID sets the "message_id" field.
func (u *SupportTicketAttachmentUpsertBulk) SetMessageID(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateMessageID() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateMessageID()
	})
}

// SetUploaderID sets the "uploader_id" field.
func (u *SupportTicketAttachmentUpsertBulk) SetUploaderID(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetUploaderID(v)
	})
}

// UpdateUploaderID sets the "uploader_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateUploaderID() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateUploaderID()
	})
}

// SetOriginalName sets the "original_name" field.
func (u *SupportTicketAttachmentUpsertBulk) SetOriginalName(v string) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetOriginalName(v)
	})
}

// UpdateOriginalName sets the "original_name" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateOriginalName() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateOriginalName()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *SupportTicketAttachmentUpsertBulk) SetStorageKey(v string) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateStorageKey() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateStorageKey()
	})
}

// SetMediaType sets the "media_type" field.
func (u *SupportTicketAttachmentUpsertBulk) SetMediaType(v string) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetMediaType(v)
	})
}

// UpdateMediaType sets the "media_type" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateMediaType() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateMediaType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *SupportTicketAttachmentUpsertBulk) SetSizeBytes(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *SupportTicketAttachmentUpsertBulk) AddSizeBytes(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateSizeBytes() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetDeleteAfter sets the "delete_after" field.
func (u *SupportTicketAttachmentUpsertBulk) SetDeleteAfter(v time.Time) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetDeleteAfter(v)
	})
}

// UpdateDeleteAfter sets the "delete_after" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateDeleteAfter() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateDeleteAfter()
	})
}

// ClearDeleteAfter clears the value of the "delete_after" field.
func (u *SupportTicketAttachmentUpsertBulk) ClearDeleteAfter() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearDeleteAfter()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SupportTicketAttachmentUpsertBulk) SetDeletedAt(v time.Time) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateDeletedAt() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SupportTicketAttachmentUpsertBulk) ClearDeletedAt() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *SupportTicketAttachmentUpsertBulk) SetDeletedBy(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateDeletedBy() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *SupportTicketAttachmentUpsertBulk) ClearDeletedBy() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearDeletedBy()
	})
}

// SetDeleteReason sets the "delete_reason" field.
func (u *SupportTicketAttachmentUpsertBulk) SetDeleteReason(v string) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetDeleteReason(v)
	})
}

// UpdateDeleteReason sets the "delete_reason" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateDeleteReason() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateDeleteReason()
	})
}

// ClearDeleteReason clears the value of the "delete_reason" field.
func (u *SupportTicketAttachmentUpsertBulk) ClearDeleteReason() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearDeleteReason()
	})
}

// Exec executes the query.
func (u *SupportTicketAttachmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SupportTicketAttachmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportTicketAttachmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportTicketAttachmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
