// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
	"github.com/Wei-Shaw/sub2api/ent/supportticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/supportticketread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportTicketUpdate is the builder for updating SupportTicket entities.
type SupportTicketUpdate struct {
	config
	hooks    []Hook
	mutation *SupportTicketMutation
}

// Where appends a list predicates to the SupportTicketUpdate builder.
func (_u *SupportTicketUpdate) Where(ps ...predicate.SupportTicket) *SupportTicketUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SupportTicketUpdate) SetUserID(v int64) *SupportTicketUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableUserID(v *int64) *SupportTicketUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *SupportTicketUpdate) SetSubject(v string) *SupportTicketUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableSubject(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SupportTicketUpdate) SetCategory(v string) *SupportTicketUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableCategory(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportTicketUpdate) SetStatus(v string) *SupportTicketUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableStatus(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SupportTicketUpdate) SetPriority(v string) *SupportTicketUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillablePriority(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetAssigneeID sets the "assignee_id" field.
func (_u *SupportTicketUpdate) SetAssigneeID(v int64) *SupportTicketUpdate {
	_u.mutation.SetAssigneeID(v)
	return _u
}

// SetNillableAssigneeID sets the "assignee_id" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableAssigneeID(v *int64) *SupportTicketUpdate {
	if v != nil {
		_u.SetAssigneeID(*v)
	}
	return _u
}

// ClearAssigneeID clears the value of the "assignee_id" field.
func (_u *SupportTicketUpdate) ClearAssigneeID() *SupportTicketUpdate {
	_u.mutation.ClearAssigneeID()
	return _u
}

// SetClosedBy sets the "closed_by" field.
func (_u *SupportTicketUpdate) SetClosedBy(v int64) *SupportTicketUpdate {
	_u.mutation.SetClosedBy(v)
	return _u
}

// SetNillableClosedBy sets the "closed_by" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableClosedBy(v *int64) *SupportTicketUpdate {
	if v != nil {
		_u.SetClosedBy(*v)
	}
	return _u
}

// ClearClosedBy clears the value of the "closed_by" field.
func (_u *SupportTicketUpdate) ClearClosedBy() *SupportTicketUpdate {
	_u.mutation.ClearClosedBy()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *SupportTicketUpdate) SetClosedAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableClosedAt(v *time.Time) *SupportTicketUpdate {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *SupportTicketUpdate) ClearClosedAt() *SupportTicketUpdate {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *SupportTicketUpdate) SetLastMessageAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableLastMessageAt(v *time.Time) *SupportTicketUpdate {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketUpdate) SetUpdatedAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SupportTicketUpdate) SetUser(v *User) *SupportTicketUpdate {
	return _u.SetUserID(v.ID)
}

// SetAssignee sets the "assignee" edge to the User entity.
func (_u *SupportTicketUpdate) SetAssignee(v *User) *SupportTicketUpdate {
	return _u.SetAssigneeID(v.ID)
}

// SetClosedByUserID sets the "closed_by_user" edge to the User entity by ID.
func (_u *SupportTicketUpdate) SetClosedByUserID(id int64) *SupportTicketUpdate {
	_u.mutation.SetClosedByUserID(id)
	return _u
}

// SetNillableClosedByUserID sets the "closed_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableClosedByUserID(id *int64) *SupportTicketUpdate {
	if id != nil {
		_u = _u.SetClosedByUserID(*id)
	}
	return _u
}

// SetClosedByUser sets the "closed_by_user" edge to the User entity.
func (_u *SupportTicketUpdate) SetClosedByUser(v *User) *SupportTicketUpdate {
	return _u.SetClosedByUserID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the SupportTicketMessage entity by IDs.
func (_u *SupportTicketUpdate) AddMessageIDs(ids ...int64) *SupportTicketUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the SupportTicketMessage entity.
func (_u *SupportTicketUpdate) AddMessages(v ...*SupportTicketMessage) *SupportTicketUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// AddReadIDs adds the "reads" edge to the SupportTicketRead entity by IDs.
func (_u *SupportTicketUpdate) AddReadIDs(ids ...int64) *SupportTicketUpdate {
	_u.mutation.AddReadIDs(ids...)
	return _u
}

// AddReads adds the "reads" edges to the SupportTicketRead entity.
func (_u *SupportTicketUpdate) AddReads(v ...*SupportTicketRead) *SupportTicketUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReadIDs(ids...)
}

// Mutation returns the SupportTicketMutation object of the builder.
func (_u *SupportTicketUpdate) Mutation() *SupportTicketMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SupportTicketUpdate) ClearUser() *SupportTicketUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAssignee clears the "assignee" edge to the User entity.
func (_u *SupportTicketUpdate) ClearAssignee() *SupportTicketUpdate {
	_u.mutation.ClearAssignee()
	return _u
}

// ClearClosedByUser clears the "closed_by_user" edge to the User entity.
func (_u *SupportTicketUpdate) ClearClosedByUser() *SupportTicketUpdate {
	_u.mutation.ClearClosedByUser()
	return _u
}

// ClearMessages clears all "messages" edges to the SupportTicketMessage entity.
func (_u *SupportTicketUpdate) ClearMessages() *SupportTicketUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to SupportTicketMessage entities by IDs.
func (_u *SupportTicketUpdate) RemoveMessageIDs(ids ...int64) *SupportTicketUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to SupportTicketMessage entities.
func (_u *SupportTicketUpdate) RemoveMessages(v ...*SupportTicketMessage) *SupportTicketUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// ClearReads clears all "reads" edges to the SupportTicketRead entity.
func (_u *SupportTicketUpdate) ClearReads() *SupportTicketUpdate {
	_u.mutation.ClearReads()
	return _u
}

// RemoveReadIDs removes the "reads" edge to SupportTicketRead entities by IDs.
func (_u *SupportTicketUpdate) RemoveReadIDs(ids ...int64) *SupportTicketUpdate {
	_u.mutation.RemoveReadIDs(ids...)
	return _u
}

// RemoveReads removes "reads" edges to SupportTicketRead entities.
func (_u *SupportTicketUpdate) RemoveReads(v ...*SupportTicketRead) *SupportTicketUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReadIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportTicketUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportTicketUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketUpdate) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := supportticket.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := supportticket.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := supportticket.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.priority": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicket.user"`)
	}
	return nil
}

func (_u *SupportTicketUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticket.Table, supportticket.Columns, sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(supportticket.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(supportticket.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportticket.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(supportticket.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(supportticket.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(supportticket.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(supportticket.FieldLastMessageAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticket.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.UserTable,
			Columns: []string{supportticket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.UserTable,
			Columns: []string{supportticket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssigneeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.AssigneeTable,
			Columns: []string{supportticket.AssigneeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssigneeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.AssigneeTable,
			Columns: []string{supportticket.AssigneeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClosedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.ClosedByUserTable,
			Columns: []string{supportticket.ClosedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClosedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.ClosedByUserTable,
			Columns: []string{supportticket.ClosedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.ReadsTable,
			Columns: []string{supportticket.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketread.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReadsIDs(); len(nodes) > 0 && !_u.mutation.ReadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.ReadsTable,
			Columns: []string{supportticket.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketread.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.ReadsTable,
			Columns: []string{supportticket.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketread.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportTicketUpdateOne is the builder for updating a single SupportTicket entity.
type SupportTicketUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportTicketMutation
}

// SetUserID sets the "user_id" field.
func (_u *SupportTicketUpdateOne) SetUserID(v int64) *SupportTicketUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableUserID(v *int64) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *SupportTicketUpdateOne) SetSubject(v string) *SupportTicketUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableSubject(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SupportTicketUpdateOne) SetCategory(v string) *SupportTicketUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableCategory(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportTicketUpdateOne) SetStatus(v string) *SupportTicketUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableStatus(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SupportTicketUpdateOne) SetPriority(v string) *SupportTicketUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillablePriority(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetAssigneeID sets the "assignee_id" field.
func (_u *SupportTicketUpdateOne) SetAssigneeID(v int64) *SupportTicketUpdateOne {
	_u.mutation.SetAssigneeID(v)
	return _u
}

// SetNillableAssigneeID sets the "assignee_id" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableAssigneeID(v *int64) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetAssigneeID(*v)
	}
	return _u
}

// ClearAssigneeID clears the value of the "assignee_id" field.
func (_u *SupportTicketUpdateOne) ClearAssigneeID() *SupportTicketUpdateOne {
	_u.mutation.ClearAssigneeID()
	return _u
}

// SetClosedBy sets the "closed_by" field.
func (_u *SupportTicketUpdateOne) SetClosedBy(v int64) *SupportTicketUpdateOne {
	_u.mutation.SetClosedBy(v)
	return _u
}

// SetNillableClosedBy sets the "closed_by" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableClosedBy(v *int64) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetClosedBy(*v)
	}
	return _u
}

// ClearClosedBy clears the value of the "closed_by" field.
func (_u *SupportTicketUpdateOne) ClearClosedBy() *SupportTicketUpdateOne {
	_u.mutation.ClearClosedBy()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *SupportTicketUpdateOne) SetClosedAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableClosedAt(v *time.Time) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *SupportTicketUpdateOne) ClearClosedAt() *SupportTicketUpdateOne {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *SupportTicketUpdateOne) SetLastMessageAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableLastMessageAt(v *time.Time) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketUpdateOne) SetUpdatedAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SupportTicketUpdateOne) SetUser(v *User) *SupportTicketUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAssignee sets the "assignee" edge to the User entity.
func (_u *SupportTicketUpdateOne) SetAssignee(v *User) *SupportTicketUpdateOne {
	return _u.SetAssigneeID(v.ID)
}

// SetClosedByUserID sets the "closed_by_user" edge to the User entity by ID.
func (_u *SupportTicketUpdateOne) SetClosedByUserID(id int64) *SupportTicketUpdateOne {
	_u.mutation.SetClosedByUserID(id)
	return _u
}

// SetNillableClosedByUserID sets the "closed_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableClosedByUserID(id *int64) *SupportTicketUpdateOne {
	if id != nil {
		_u = _u.SetClosedByUserID(*id)
	}
	return _u
}

// SetClosedByUser sets the "closed_by_user" edge to the User entity.
func (_u *SupportTicketUpdateOne) SetClosedByUser(v *User) *SupportTicketUpdateOne {
	return _u.SetClosedByUserID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the SupportTicketMessage entity by IDs.
func (_u *SupportTicketUpdateOne) AddMessageIDs(ids ...int64) *SupportTicketUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the SupportTicketMessage entity.
func (_u *SupportTicketUpdateOne) AddMessages(v ...*SupportTicketMessage) *SupportTicketUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// AddReadIDs adds the "reads" edge to the SupportTicketRead entity by IDs.
func (_u *SupportTicketUpdateOne) AddReadIDs(ids ...int64) *SupportTicketUpdateOne {
	_u.mutation.AddReadIDs(ids...)
	return _u
}

// AddReads adds the "reads" edges to the SupportTicketRead entity.
func (_u *SupportTicketUpdateOne) AddReads(v ...*SupportTicketRead) *SupportTicketUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReadIDs(ids...)
}

// Mutation returns the SupportTicketMutation object of the builder.
func (_u *SupportTicketUpdateOne) Mutation() *SupportTicketMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SupportTicketUpdateOne) ClearUser() *SupportTicketUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAssignee clears the "assignee" edge to the User entity.
func (_u *SupportTicketUpdateOne) ClearAssignee() *SupportTicketUpdateOne {
	_u.mutation.ClearAssignee()
	return _u
}

// ClearClosedByUser clears the "closed_by_user" edge to the User entity.
func (_u *SupportTicketUpdateOne) ClearClosedByUser() *SupportTicketUpdateOne {
	_u.mutation.ClearClosedByUser()
	return _u
}

// ClearMessages clears all "messages" edges to the SupportTicketMessage entity.
func (_u *SupportTicketUpdateOne) ClearMessages() *SupportTicketUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to SupportTicketMessage entities by IDs.
func (_u *SupportTicketUpdateOne) RemoveMessageIDs(ids ...int64) *SupportTicketUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to SupportTicketMessage entities.
func (_u *SupportTicketUpdateOne) RemoveMessages(v ...*SupportTicketMessage) *SupportTicketUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// ClearReads clears all "reads" edges to the SupportTicketRead entity.
func (_u *SupportTicketUpdateOne) ClearReads() *SupportTicketUpdateOne {
	_u.mutation.ClearReads()
	return _u
}

// RemoveReadIDs removes the "reads" edge to SupportTicketRead entities by IDs.
func (_u *SupportTicketUpdateOne) RemoveReadIDs(ids ...int64) *SupportTicketUpdateOne {
	_u.mutation.RemoveReadIDs(ids...)
	return _u
}

// RemoveReads removes "reads" edges to SupportTicketRead entities.
func (_u *SupportTicketUpdateOne) RemoveReads(v ...*SupportTicketRead) *SupportTicketUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReadIDs(ids...)
}

// Where appends a list predicates to the SupportTicketUpdate builder.
func (_u *SupportTicketUpdateOne) Where(ps ...predicate.SupportTicket) *SupportTicketUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportTicketUpdateOne) Select(field string, fields ...string) *SupportTicketUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportTicket entity.
func (_u *SupportTicketUpdateOne) Save(ctx context.Context) (*SupportTicket, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketUpdateOne) SaveX(ctx context.Context) *SupportTicket {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportTicketUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketUpdateOne) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := supportticket.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := supportticket.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := supportticket.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.priority": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicket.user"`)
	}
	return nil
}

func (_u *SupportTicketUpdateOne) sqlSave(ctx context.Context) (_node *SupportTicket, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticket.Table, supportticket.Columns, sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportTicket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportticket.FieldID)
		for _, f := range fields {
			if !supportticket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportticket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(supportticket.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(supportticket.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportticket.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(supportticket.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(supportticket.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(supportticket.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(supportticket.FieldLastMessageAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticket.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.UserTable,
			Columns: []string{supportticket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.UserTable,
			Columns: []string{supportticket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssigneeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.AssigneeTable,
			Columns: []string{supportticket.AssigneeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssigneeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.AssigneeTable,
			Columns: []string{supportticket.AssigneeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClosedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.ClosedByUserTable,
			Columns: []string{supportticket.ClosedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClosedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.ClosedByUserTable,
			Columns: []string{supportticket.ClosedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.ReadsTable,
			Columns: []string{supportticket.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketread.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReadsIDs(); len(nodes) > 0 && !_u.mutation.ReadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.ReadsTable,
			Columns: []string{supportticket.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketread.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.ReadsTable,
			Columns: []string{supportticket.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketread.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupportTicket{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
