// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportticketattachment"
	"github.com/Wei-Shaw/sub2api/ent/supportticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportTicketAttachmentUpdate is the builder for updating SupportTicketAttachment entities.
type SupportTicketAttachmentUpdate struct {
	config
	hooks    []Hook
	mutation *SupportTicketAttachmentMutation
}

// Where appends a list predicates to the SupportTicketAttachmentUpdate builder.
func (_u *SupportTicketAttachmentUpdate) Where(ps ...predicate.SupportTicketAttachment) *SupportTicketAttachmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *SupportTicketAttachmentUpdate) SetMessageID(v int64) *SupportTicketAttachmentUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableMessageID(v *int64) *SupportTicketAttachmentUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetUploaderID sets the "uploader_id" field.
func (_u *SupportTicketAttachmentUpdate) SetUploaderID(v int64) *SupportTicketAttachmentUpdate {
	_u.mutation.SetUploaderID(v)
	return _u
}

// SetNillableUploaderID sets the "uploader_id" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableUploaderID(v *int64) *SupportTicketAttachmentUpdate {
	if v != nil {
		_u.SetUploaderID(*v)
	}
	return _u
}

// SetOriginalName sets the "original_name" field.
func (_u *SupportTicketAttachmentUpdate) SetOriginalName(v string) *SupportTicketAttachmentUpdate {
	_u.mutation.SetOriginalName(v)
	return _u
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableOriginalName(v *string) *SupportTicketAttachmentUpdate {
	if v != nil {
		_u.SetOriginalName(*v)
	}
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *SupportTicketAttachmentUpdate) SetStorageKey(v string) *SupportTicketAttachmentUpdate {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableStorageKey(v *string) *SupportTicketAttachmentUpdate {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// SetMediaType sets the "media_type" field.
func (_u *SupportTicketAttachmentUpdate) SetMediaType(v string) *SupportTicketAttachmentUpdate {
	_u.mutation.SetMediaType(v)
	return _u
}

// SetNillableMediaType sets the "media_type" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableMediaType(v *string) *SupportTicketAttachmentUpdate {
	if v != nil {
		_u.SetMediaType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *SupportTicketAttachmentUpdate) SetSizeBytes(v int64) *SupportTicketAttachmentUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableSizeBytes(v *int64) *SupportTicketAttachmentUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *SupportTicketAttachmentUpdate) AddSizeBytes(v int64) *SupportTicketAttachmentUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetDeleteAfter sets the "delete_after" field.
func (_u *SupportTicketAttachmentUpdate) SetDeleteAfter(v time.Time) *SupportTicketAttachmentUpdate {
	_u.mutation.SetDeleteAfter(v)
	return _u
}

// SetNillableDeleteAfter sets the "delete_after" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableDeleteAfter(v *time.Time) *SupportTicketAttachmentUpdate {
	if v != nil {
		_u.SetDeleteAfter(*v)
	}
	return _u
}

// ClearDeleteAfter clears the value of the "delete_after" field.
func (_u *SupportTicketAttachmentUpdate) ClearDeleteAfter() *SupportTicketAttachmentUpdate {
	_u.mutation.ClearDeleteAfter()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SupportTicketAttachmentUpdate) SetDeletedAt(v time.Time) *SupportTicketAttachmentUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableDeletedAt(v *time.Time) *SupportTicketAttachmentUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SupportTicketAttachmentUpdate) ClearDeletedAt() *SupportTicketAttachmentUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *SupportTicketAttachmentUpdate) SetDeletedBy(v int64) *SupportTicketAttachmentUpdate {
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableDeletedBy(v *int64) *SupportTicketAttachmentUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *SupportTicketAttachmentUpdate) ClearDeletedBy() *SupportTicketAttachmentUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetDeleteReason sets the "delete_reason" field.
func (_u *SupportTicketAttachmentUpdate) SetDeleteReason(v string) *SupportTicketAttachmentUpdate {
	_u.mutation.SetDeleteReason(v)
	return _u
}

// SetNillableDeleteReason sets the "delete_reason" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableDeleteReason(v *string) *SupportTicketAttachmentUpdate {
	if v != nil {
		_u.SetDeleteReason(*v)
	}
	return _u
}

// ClearDeleteReason clears the value of the "delete_reason" field.
func (_u *SupportTicketAttachmentUpdate) ClearDeleteReason() *SupportTicketAttachmentUpdate {
	_u.mutation.ClearDeleteReason()
	return _u
}

// SetMessage sets the "message" edge to the SupportTicketMessage entity.
func (_u *SupportTicketAttachmentUpdate) SetMessage(v *SupportTicketMessage) *SupportTicketAttachmentUpdate {
	return _u.SetMessageID(v.ID)
}

// SetUploader sets the "uploader" edge to the User entity.
func (_u *SupportTicketAttachmentUpdate) SetUploader(v *User) *SupportTicketAttachmentUpdate {
	return _u.SetUploaderID(v.ID)
}

// SetDeletedByUserID sets the "deleted_by_user" edge to the User entity by ID.
func (_u *SupportTicketAttachmentUpdate) SetDeletedByUserID(id int64) *SupportTicketAttachmentUpdate {
	_u.mutation.SetDeletedByUserID(id)
	return _u
}

// SetNillableDeletedByUserID sets the "deleted_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableDeletedByUserID(id *int64) *SupportTicketAttachmentUpdate {
	if id != nil {
		_u = _u.SetDeletedByUserID(*id)
	}
	return _u
}

// SetDeletedByUser sets the "deleted_by_user" edge to the User entity.
func (_u *SupportTicketAttachmentUpdate) SetDeletedByUser(v *User) *SupportTicketAttachmentUpdate {
	return _u.SetDeletedByUserID(v.ID)
}

// Mutation returns the SupportTicketAttachmentMutation object of the builder.
func (_u *SupportTicketAttachmentUpdate) Mutation() *SupportTicketAttachmentMutation {
	return _u.mutation
}

// ClearMessage clears the "message" edge to the SupportTicketMessage entity.
func (_u *SupportTicketAttachmentUpdate) ClearMessage() *SupportTicketAttachmentUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// ClearUploader clears the "uploader" edge to the User entity.
func (_u *SupportTicketAttachmentUpdate) ClearUploader() *SupportTicketAttachmentUpdate {
	_u.mutation.ClearUploader()
	return _u
}

// ClearDeletedByUser clears the "deleted_by_user" edge to the User entity.
func (_u *SupportTicketAttachmentUpdate) ClearDeletedByUser() *SupportTicketAttachmentUpdate {
	_u.mutation.ClearDeletedByUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportTicketAttachmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketAttachmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportTicketAttachmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketAttachmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketAttachmentUpdate) check() error {
	if v, ok := _u.mutation.OriginalName(); ok {
		if err := supportticketattachment.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.original_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StorageKey(); ok {
		if err := supportticketattachment.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.storage_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MediaType(); ok {
		if err := supportticketattachment.MediaTypeValidator(v); err != nil {
			return &ValidationError{Name: "media_type", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.media_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeleteReason(); ok {
		if err := supportticketattachment.DeleteReasonValidator(v); err != nil {
			return &ValidationError{Name: "delete_reason", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.delete_reason": %w`, err)}
		}
	}
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketAttachment.message"`)
	}
	if _u.mutation.UploaderCleared() && len(_u.mutation.UploaderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketAttachment.uploader"`)
	}
	return nil
}

func (_u *SupportTicketAttachmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticketattachment.Table, supportticketattachment.Columns, sqlgraph.NewFieldSpec(supportticketattachment.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OriginalName(); ok {
		_spec.SetField(supportticketattachment.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(supportticketattachment.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.MediaType(); ok {
		_spec.SetField(supportticketattachment.FieldMediaType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(supportticketattachment.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(supportticketattachment.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeleteAfter(); ok {
		_spec.SetField(supportticketattachment.FieldDeleteAfter, field.TypeTime, value)
	}
	if _u.mutation.DeleteAfterCleared() {
		_spec.ClearField(supportticketattachment.FieldDeleteAfter, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(supportticketattachment.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(supportticketattachment.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteReason(); ok {
		_spec.SetField(supportticketattachment.FieldDeleteReason, field.TypeString, value)
	}
	if _u.mutation.DeleteReasonCleared() {
		_spec.ClearField(supportticketattachment.FieldDeleteReason, field.TypeString)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.MessageTable,
			Columns: []string{supportticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.MessageTable,
			Columns: []string{supportticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UploaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.UploaderTable,
			Columns: []string{supportticketattachment.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.UploaderTable,
			Columns: []string{supportticketattachment.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeletedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.DeletedByUserTable,
			Columns: []string{supportticketattachment.DeletedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeletedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.DeletedByUserTable,
			Columns: []string{supportticketattachment.DeletedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticketattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportTicketAttachmentUpdateOne is the builder for updating a single SupportTicketAttachment entity.
type SupportTicketAttachmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportTicketAttachmentMutation
}

// SetMessageID sets the "message_id" field.
func (_u *SupportTicketAttachmentUpdateOne) SetMessageID(v int64) *SupportTicketAttachmentUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableMessageID(v *int64) *SupportTicketAttachmentUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetUploaderID sets the "uploader_id" field.
func (_u *SupportTicketAttachmentUpdateOne) SetUploaderID(v int64) *SupportTicketAttachmentUpdateOne {
	_u.mutation.SetUploaderID(v)
	return _u
}

// SetNillableUploaderID sets the "uploader_id" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableUploaderID(v *int64) *SupportTicketAttachmentUpdateOne {
	if v != nil {
		_u.SetUploaderID(*v)
	}
	return _u
}

// SetOriginalName sets the "original_name" field.
func (_u *SupportTicketAttachmentUpdateOne) SetOriginalName(v string) *SupportTicketAttachmentUpdateOne {
	_u.mutation.SetOriginalName(v)
	return _u
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableOriginalName(v *string) *SupportTicketAttachmentUpdateOne {
	if v != nil {
		_u.SetOriginalName(*v)
	}
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *SupportTicketAttachmentUpdateOne) SetStorageKey(v string) *SupportTicketAttachmentUpdateOne {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableStorageKey(v *string) *SupportTicketAttachmentUpdateOne {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// SetMediaType sets the "media_type" field.
func (_u *SupportTicketAttachmentUpdateOne) SetMediaType(v string) *SupportTicketAttachmentUpdateOne {
	_u.mutation.SetMediaType(v)
	return _u
}

// SetNillableMediaType sets the "media_type" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableMediaType(v *string) *SupportTicketAttachmentUpdateOne {
	if v != nil {
		_u.SetMediaType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *SupportTicketAttachmentUpdateOne) SetSizeBytes(v int64) *SupportTicketAttachmentUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableSizeBytes(v *int64) *SupportTicketAttachmentUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *SupportTicketAttachmentUpdateOne) AddSizeBytes(v int64) *SupportTicketAttachmentUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetDeleteAfter sets the "delete_after" field.
func (_u *SupportTicketAttachmentUpdateOne) SetDeleteAfter(v time.Time) *SupportTicketAttachmentUpdateOne {
	_u.mutation.SetDeleteAfter(v)
	return _u
}

// SetNillableDeleteAfter sets the "delete_after" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableDeleteAfter(v *time.Time) *SupportTicketAttachmentUpdateOne {
	if v != nil {
		_u.SetDeleteAfter(*v)
	}
	return _u
}

// ClearDeleteAfter clears the value of the "delete_after" field.
func (_u *SupportTicketAttachmentUpdateOne) ClearDeleteAfter() *SupportTicketAttachmentUpdateOne {
	_u.mutation.ClearDeleteAfter()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SupportTicketAttachmentUpdateOne) SetDeletedAt(v time.Time) *SupportTicketAttachmentUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableDeletedAt(v *time.Time) *SupportTicketAttachmentUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SupportTicketAttachmentUpdateOne) ClearDeletedAt() *SupportTicketAttachmentUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *SupportTicketAttachmentUpdateOne) SetDeletedBy(v int64) *SupportTicketAttachmentUpdateOne {
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableDeletedBy(v *int64) *SupportTicketAttachmentUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *SupportTicketAttachmentUpdateOne) ClearDeletedBy() *SupportTicketAttachmentUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetDeleteReason sets the "delete_reason" field.
func (_u *SupportTicketAttachmentUpdateOne) SetDeleteReason(v string) *SupportTicketAttachmentUpdateOne {
	_u.mutation.SetDeleteReason(v)
	return _u
}

// SetNillableDeleteReason sets the "delete_reason" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableDeleteReason(v *string) *SupportTicketAttachmentUpdateOne {
	if v != nil {
		_u.SetDeleteReason(*v)
	}
	return _u
}

// ClearDeleteReason clears the value of the "delete_reason" field.
func (_u *SupportTicketAttachmentUpdateOne) ClearDeleteReason() *SupportTicketAttachmentUpdateOne {
	_u.mutation.ClearDeleteReason()
	return _u
}

// SetMessage sets the "message" edge to the SupportTicketMessage entity.
func (_u *SupportTicketAttachmentUpdateOne) SetMessage(v *SupportTicketMessage) *SupportTicketAttachmentUpdateOne {
	return _u.SetMessageID(v.ID)
}

// SetUploader sets the "uploader" edge to the User entity.
func (_u *SupportTicketAttachmentUpdateOne) SetUploader(v *User) *SupportTicketAttachmentUpdateOne {
	return _u.SetUploaderID(v.ID)
}

// SetDeletedByUserID sets the "deleted_by_user" edge to the User entity by ID.
func (_u *SupportTicketAttachmentUpdateOne) SetDeletedByUserID(id int64) *SupportTicketAttachmentUpdateOne {
	_u.mutation.SetDeletedByUserID(id)
	return _u
}

// SetNillableDeletedByUserID sets the "deleted_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableDeletedByUserID(id *int64) *SupportTicketAttachmentUpdateOne {
	if id != nil {
		_u = _u.SetDeletedByUserID(*id)
	}
	return _u
}

// SetDeletedByUser sets the "deleted_by_user" edge to the User entity.
func (_u *SupportTicketAttachmentUpdateOne) SetDeletedByUser(v *User) *SupportTicketAttachmentUpdateOne {
	return _u.SetDeletedByUserID(v.ID)
}

// Mutation returns the SupportTicketAttachmentMutation object of the builder.
func (_u *SupportTicketAttachmentUpdateOne) Mutation() *SupportTicketAttachmentMutation {
	return _u.mutation
}

// ClearMessage clears the "message" edge to the SupportTicketMessage entity.
func (_u *SupportTicketAttachmentUpdateOne) ClearMessage() *SupportTicketAttachmentUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// ClearUploader clears the "uploader" edge to the User entity.
func (_u *SupportTicketAttachmentUpdateOne) ClearUploader() *SupportTicketAttachmentUpdateOne {
	_u.mutation.ClearUploader()
	return _u
}

// ClearDeletedByUser clears the "deleted_by_user" edge to the User entity.
func (_u *SupportTicketAttachmentUpdateOne) ClearDeletedByUser() *SupportTicketAttachmentUpdateOne {
	_u.mutation.ClearDeletedByUser()
	return _u
}

// Where appends a list predicates to the SupportTicketAttachmentUpdate builder.
func (_u *SupportTicketAttachmentUpdateOne) Where(ps ...predicate.SupportTicketAttachment) *SupportTicketAttachmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportTicketAttachmentUpdateOne) Select(field string, fields ...string) *SupportTicketAttachmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportTicketAttachment entity.
func (_u *SupportTicketAttachmentUpdateOne) Save(ctx context.Context) (*SupportTicketAttachment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketAttachmentUpdateOne) SaveX(ctx context.Context) *SupportTicketAttachment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportTicketAttachmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketAttachmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketAttachmentUpdateOne) check() error {
	if v, ok := _u.mutation.OriginalName(); ok {
		if err := supportticketattachment.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.original_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StorageKey(); ok {
		if err := supportticketattachment.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.storage_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MediaType(); ok {
		if err := supportticketattachment.MediaTypeValidator(v); err != nil {
			return &ValidationError{Name: "media_type", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.media_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeleteReason(); ok {
		if err := supportticketattachment.DeleteReasonValidator(v); err != nil {
			return &ValidationError{Name: "delete_reason", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.delete_reason": %w`, err)}
		}
	}
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketAttachment.message"`)
	}
	if _u.mutation.UploaderCleared() && len(_u.mutation.UploaderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketAttachment.uploader"`)
	}
	return nil
}

func (_u *SupportTicketAttachmentUpdateOne) sqlSave(ctx context.Context) (_node *SupportTicketAttachment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticketattachment.Table, supportticketattachment.Columns, sqlgraph.NewFieldSpec(supportticketattachment.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportTicketAttachment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportticketattachment.FieldID)
		for _, f := range fields {
			if !supportticketattachment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportticketattachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OriginalName(); ok {
		_spec.SetField(supportticketattachment.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(supportticketattachment.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.MediaType(); ok {
		_spec.SetField(supportticketattachment.FieldMediaType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(supportticketattachment.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(supportticketattachment.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeleteAfter(); ok {
		_spec.SetField(supportticketattachment.FieldDeleteAfter, field.TypeTime, value)
	}
	if _u.mutation.DeleteAfterCleared() {
		_spec.ClearField(supportticketattachment.FieldDeleteAfter, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(supportticketattachment.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(supportticketattachment.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteReason(); ok {
		_spec.SetField(supportticketattachment.FieldDeleteReason, field.TypeString, value)
	}
	if _u.mutation.DeleteReasonCleared() {
		_spec.ClearField(supportticketattachment.FieldDeleteReason, field.TypeString)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.MessageTable,
			Columns: []string{supportticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.MessageTable,
			Columns: []string{supportticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UploaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.UploaderTable,
			Columns: []string{supportticketattachment.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.UploaderTable,
			Columns: []string{supportticketattachment.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeletedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.DeletedByUserTable,
			Columns: []string{supportticketattachment.DeletedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeletedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.DeletedByUserTable,
			Columns: []string{supportticketattachment.DeletedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupportTicketAttachment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticketattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
