// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/videotask"
)

// VideoTaskUpdate is the builder for updating VideoTask entities.
type VideoTaskUpdate struct {
	config
	hooks    []Hook
	mutation *VideoTaskMutation
}

// Where appends a list predicates to the VideoTaskUpdate builder.
func (_u *VideoTaskUpdate) Where(ps ...predicate.VideoTask) *VideoTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *VideoTaskUpdate) SetUpstreamTaskID(v string) *VideoTaskUpdate {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUpstreamTaskID(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// SetBillingRequestID sets the "billing_request_id" field.
func (_u *VideoTaskUpdate) SetBillingRequestID(v string) *VideoTaskUpdate {
	_u.mutation.SetBillingRequestID(v)
	return _u
}

// SetNillableBillingRequestID sets the "billing_request_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableBillingRequestID(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetBillingRequestID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *VideoTaskUpdate) SetUserID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUserID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *VideoTaskUpdate) AddUserID(v int64) *VideoTaskUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *VideoTaskUpdate) SetAPIKeyID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableAPIKeyID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *VideoTaskUpdate) AddAPIKeyID(v int64) *VideoTaskUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *VideoTaskUpdate) SetAccountID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableAccountID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *VideoTaskUpdate) AddAccountID(v int64) *VideoTaskUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *VideoTaskUpdate) SetGroupID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableGroupID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *VideoTaskUpdate) AddGroupID(v int64) *VideoTaskUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetRefundAmount sets the "refund_amount" field.
func (_u *VideoTaskUpdate) SetRefundAmount(v float64) *VideoTaskUpdate {
	_u.mutation.ResetRefundAmount()
	_u.mutation.SetRefundAmount(v)
	return _u
}

// SetNillableRefundAmount sets the "refund_amount" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableRefundAmount(v *float64) *VideoTaskUpdate {
	if v != nil {
		_u.SetRefundAmount(*v)
	}
	return _u
}

// AddRefundAmount adds value to the "refund_amount" field.
func (_u *VideoTaskUpdate) AddRefundAmount(v float64) *VideoTaskUpdate {
	_u.mutation.AddRefundAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *VideoTaskUpdate) SetStatus(v string) *VideoTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableStatus(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNextPollAt sets the "next_poll_at" field.
func (_u *VideoTaskUpdate) SetNextPollAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetNextPollAt(v)
	return _u
}

// SetNillableNextPollAt sets the "next_poll_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableNextPollAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetNextPollAt(*v)
	}
	return _u
}

// SetLockedUntil sets the "locked_until" field.
func (_u *VideoTaskUpdate) SetLockedUntil(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetLockedUntil(v)
	return _u
}

// SetNillableLockedUntil sets the "locked_until" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableLockedUntil(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetLockedUntil(*v)
	}
	return _u
}

// ClearLockedUntil clears the value of the "locked_until" field.
func (_u *VideoTaskUpdate) ClearLockedUntil() *VideoTaskUpdate {
	_u.mutation.ClearLockedUntil()
	return _u
}

// SetPollAttempts sets the "poll_attempts" field.
func (_u *VideoTaskUpdate) SetPollAttempts(v int) *VideoTaskUpdate {
	_u.mutation.ResetPollAttempts()
	_u.mutation.SetPollAttempts(v)
	return _u
}

// SetNillablePollAttempts sets the "poll_attempts" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillablePollAttempts(v *int) *VideoTaskUpdate {
	if v != nil {
		_u.SetPollAttempts(*v)
	}
	return _u
}

// AddPollAttempts adds value to the "poll_attempts" field.
func (_u *VideoTaskUpdate) AddPollAttempts(v int) *VideoTaskUpdate {
	_u.mutation.AddPollAttempts(v)
	return _u
}

// SetTerminalAt sets the "terminal_at" field.
func (_u *VideoTaskUpdate) SetTerminalAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetTerminalAt(v)
	return _u
}

// SetNillableTerminalAt sets the "terminal_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableTerminalAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetTerminalAt(*v)
	}
	return _u
}

// ClearTerminalAt clears the value of the "terminal_at" field.
func (_u *VideoTaskUpdate) ClearTerminalAt() *VideoTaskUpdate {
	_u.mutation.ClearTerminalAt()
	return _u
}

// SetRefundedAt sets the "refunded_at" field.
func (_u *VideoTaskUpdate) SetRefundedAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetRefundedAt(v)
	return _u
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableRefundedAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetRefundedAt(*v)
	}
	return _u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (_u *VideoTaskUpdate) ClearRefundedAt() *VideoTaskUpdate {
	_u.mutation.ClearRefundedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *VideoTaskUpdate) SetLastError(v string) *VideoTaskUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableLastError(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *VideoTaskUpdate) ClearLastError() *VideoTaskUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoTaskUpdate) SetUpdatedAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the VideoTaskMutation object of the builder.
func (_u *VideoTaskUpdate) Mutation() *VideoTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VideoTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VideoTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videotask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoTaskUpdate) check() error {
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := videotask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingRequestID(); ok {
		if err := videotask.BillingRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "billing_request_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.billing_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := videotask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.status": %w`, err)}
		}
	}
	return nil
}

func (_u *VideoTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videotask.Table, videotask.Columns, sqlgraph.NewFieldSpec(videotask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(videotask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingRequestID(); ok {
		_spec.SetField(videotask.FieldBillingRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(videotask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(videotask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(videotask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(videotask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(videotask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(videotask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(videotask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(videotask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefundAmount(); ok {
		_spec.SetField(videotask.FieldRefundAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefundAmount(); ok {
		_spec.AddField(videotask.FieldRefundAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(videotask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.NextPollAt(); ok {
		_spec.SetField(videotask.FieldNextPollAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LockedUntil(); ok {
		_spec.SetField(videotask.FieldLockedUntil, field.TypeTime, value)
	}
	if _u.mutation.LockedUntilCleared() {
		_spec.ClearField(videotask.FieldLockedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.PollAttempts(); ok {
		_spec.SetField(videotask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPollAttempts(); ok {
		_spec.AddField(videotask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TerminalAt(); ok {
		_spec.SetField(videotask.FieldTerminalAt, field.TypeTime, value)
	}
	if _u.mutation.TerminalAtCleared() {
		_spec.ClearField(videotask.FieldTerminalAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RefundedAt(); ok {
		_spec.SetField(videotask.FieldRefundedAt, field.TypeTime, value)
	}
	if _u.mutation.RefundedAtCleared() {
		_spec.ClearField(videotask.FieldRefundedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(videotask.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(videotask.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videotask.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videotask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VideoTaskUpdateOne is the builder for updating a single VideoTask entity.
type VideoTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VideoTaskMutation
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *VideoTaskUpdateOne) SetUpstreamTaskID(v string) *VideoTaskUpdateOne {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUpstreamTaskID(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// SetBillingRequestID sets the "billing_request_id" field.
func (_u *VideoTaskUpdateOne) SetBillingRequestID(v string) *VideoTaskUpdateOne {
	_u.mutation.SetBillingRequestID(v)
	return _u
}

// SetNillableBillingRequestID sets the "billing_request_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableBillingRequestID(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetBillingRequestID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *VideoTaskUpdateOne) SetUserID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUserID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *VideoTaskUpdateOne) AddUserID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *VideoTaskUpdateOne) SetAPIKeyID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableAPIKeyID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *VideoTaskUpdateOne) AddAPIKeyID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *VideoTaskUpdateOne) SetAccountID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableAccountID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *VideoTaskUpdateOne) AddAccountID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *VideoTaskUpdateOne) SetGroupID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableGroupID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *VideoTaskUpdateOne) AddGroupID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetRefundAmount sets the "refund_amount" field.
func (_u *VideoTaskUpdateOne) SetRefundAmount(v float64) *VideoTaskUpdateOne {
	_u.mutation.ResetRefundAmount()
	_u.mutation.SetRefundAmount(v)
	return _u
}

// SetNillableRefundAmount sets the "refund_amount" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableRefundAmount(v *float64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetRefundAmount(*v)
	}
	return _u
}

// AddRefundAmount adds value to the "refund_amount" field.
func (_u *VideoTaskUpdateOne) AddRefundAmount(v float64) *VideoTaskUpdateOne {
	_u.mutation.AddRefundAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *VideoTaskUpdateOne) SetStatus(v string) *VideoTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableStatus(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNextPollAt sets the "next_poll_at" field.
func (_u *VideoTaskUpdateOne) SetNextPollAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetNextPollAt(v)
	return _u
}

// SetNillableNextPollAt sets the "next_poll_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableNextPollAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetNextPollAt(*v)
	}
	return _u
}

// SetLockedUntil sets the "locked_until" field.
func (_u *VideoTaskUpdateOne) SetLockedUntil(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetLockedUntil(v)
	return _u
}

// SetNillableLockedUntil sets the "locked_until" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableLockedUntil(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetLockedUntil(*v)
	}
	return _u
}

// ClearLockedUntil clears the value of the "locked_until" field.
func (_u *VideoTaskUpdateOne) ClearLockedUntil() *VideoTaskUpdateOne {
	_u.mutation.ClearLockedUntil()
	return _u
}

// SetPollAttempts sets the "poll_attempts" field.
func (_u *VideoTaskUpdateOne) SetPollAttempts(v int) *VideoTaskUpdateOne {
	_u.mutation.ResetPollAttempts()
	_u.mutation.SetPollAttempts(v)
	return _u
}

// SetNillablePollAttempts sets the "poll_attempts" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillablePollAttempts(v *int) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetPollAttempts(*v)
	}
	return _u
}

// AddPollAttempts adds value to the "poll_attempts" field.
func (_u *VideoTaskUpdateOne) AddPollAttempts(v int) *VideoTaskUpdateOne {
	_u.mutation.AddPollAttempts(v)
	return _u
}

// SetTerminalAt sets the "terminal_at" field.
func (_u *VideoTaskUpdateOne) SetTerminalAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetTerminalAt(v)
	return _u
}

// SetNillableTerminalAt sets the "terminal_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableTerminalAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetTerminalAt(*v)
	}
	return _u
}

// ClearTerminalAt clears the value of the "terminal_at" field.
func (_u *VideoTaskUpdateOne) ClearTerminalAt() *VideoTaskUpdateOne {
	_u.mutation.ClearTerminalAt()
	return _u
}

// SetRefundedAt sets the "refunded_at" field.
func (_u *VideoTaskUpdateOne) SetRefundedAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetRefundedAt(v)
	return _u
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableRefundedAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetRefundedAt(*v)
	}
	return _u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (_u *VideoTaskUpdateOne) ClearRefundedAt() *VideoTaskUpdateOne {
	_u.mutation.ClearRefundedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *VideoTaskUpdateOne) SetLastError(v string) *VideoTaskUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableLastError(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *VideoTaskUpdateOne) ClearLastError() *VideoTaskUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoTaskUpdateOne) SetUpdatedAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the VideoTaskMutation object of the builder.
func (_u *VideoTaskUpdateOne) Mutation() *VideoTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the VideoTaskUpdate builder.
func (_u *VideoTaskUpdateOne) Where(ps ...predicate.VideoTask) *VideoTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VideoTaskUpdateOne) Select(field string, fields ...string) *VideoTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VideoTask entity.
func (_u *VideoTaskUpdateOne) Save(ctx context.Context) (*VideoTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoTaskUpdateOne) SaveX(ctx context.Context) *VideoTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VideoTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videotask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoTaskUpdateOne) check() error {
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := videotask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingRequestID(); ok {
		if err := videotask.BillingRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "billing_request_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.billing_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := videotask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.status": %w`, err)}
		}
	}
	return nil
}

func (_u *VideoTaskUpdateOne) sqlSave(ctx context.Context) (_node *VideoTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videotask.Table, videotask.Columns, sqlgraph.NewFieldSpec(videotask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VideoTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, videotask.FieldID)
		for _, f := range fields {
			if !videotask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != videotask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(videotask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingRequestID(); ok {
		_spec.SetField(videotask.FieldBillingRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(videotask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(videotask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(videotask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(videotask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(videotask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(videotask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(videotask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(videotask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefundAmount(); ok {
		_spec.SetField(videotask.FieldRefundAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefundAmount(); ok {
		_spec.AddField(videotask.FieldRefundAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(videotask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.NextPollAt(); ok {
		_spec.SetField(videotask.FieldNextPollAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LockedUntil(); ok {
		_spec.SetField(videotask.FieldLockedUntil, field.TypeTime, value)
	}
	if _u.mutation.LockedUntilCleared() {
		_spec.ClearField(videotask.FieldLockedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.PollAttempts(); ok {
		_spec.SetField(videotask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPollAttempts(); ok {
		_spec.AddField(videotask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TerminalAt(); ok {
		_spec.SetField(videotask.FieldTerminalAt, field.TypeTime, value)
	}
	if _u.mutation.TerminalAtCleared() {
		_spec.ClearField(videotask.FieldTerminalAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RefundedAt(); ok {
		_spec.SetField(videotask.FieldRefundedAt, field.TypeTime, value)
	}
	if _u.mutation.RefundedAtCleared() {
		_spec.ClearField(videotask.FieldRefundedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(videotask.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(videotask.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videotask.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &VideoTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videotask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
