// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/videotask"
)

// VideoTaskCreate is the builder for creating a VideoTask entity.
type VideoTaskCreate struct {
	config
	mutation *VideoTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_c *VideoTaskCreate) SetUpstreamTaskID(v string) *VideoTaskCreate {
	_c.mutation.SetUpstreamTaskID(v)
	return _c
}

// SetBillingRequestID sets the "billing_request_id" field.
func (_c *VideoTaskCreate) SetBillingRequestID(v string) *VideoTaskCreate {
	_c.mutation.SetBillingRequestID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *VideoTaskCreate) SetUserID(v int64) *VideoTaskCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *VideoTaskCreate) SetAPIKeyID(v int64) *VideoTaskCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *VideoTaskCreate) SetAccountID(v int64) *VideoTaskCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *VideoTaskCreate) SetGroupID(v int64) *VideoTaskCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetRefundAmount sets the "refund_amount" field.
func (_c *VideoTaskCreate) SetRefundAmount(v float64) *VideoTaskCreate {
	_c.mutation.SetRefundAmount(v)
	return _c
}

// SetNillableRefundAmount sets the "refund_amount" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableRefundAmount(v *float64) *VideoTaskCreate {
	if v != nil {
		_c.SetRefundAmount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *VideoTaskCreate) SetStatus(v string) *VideoTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableStatus(v *string) *VideoTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNextPollAt sets the "next_poll_at" field.
func (_c *VideoTaskCreate) SetNextPollAt(v time.Time) *VideoTaskCreate {
	_c.mutation.SetNextPollAt(v)
	return _c
}

// SetNillableNextPollAt sets the "next_poll_at" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableNextPollAt(v *time.Time) *VideoTaskCreate {
	if v != nil {
		_c.SetNextPollAt(*v)
	}
	return _c
}

// SetLockedUntil sets the "locked_until" field.
func (_c *VideoTaskCreate) SetLockedUntil(v time.Time) *VideoTaskCreate {
	_c.mutation.SetLockedUntil(v)
	return _c
}

// SetNillableLockedUntil sets the "locked_until" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableLockedUntil(v *time.Time) *VideoTaskCreate {
	if v != nil {
		_c.SetLockedUntil(*v)
	}
	return _c
}

// SetPollAttempts sets the "poll_attempts" field.
func (_c *VideoTaskCreate) SetPollAttempts(v int) *VideoTaskCreate {
	_c.mutation.SetPollAttempts(v)
	return _c
}

// SetNillablePollAttempts sets the "poll_attempts" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillablePollAttempts(v *int) *VideoTaskCreate {
	if v != nil {
		_c.SetPollAttempts(*v)
	}
	return _c
}

// SetTerminalAt sets the "terminal_at" field.
func (_c *VideoTaskCreate) SetTerminalAt(v time.Time) *VideoTaskCreate {
	_c.mutation.SetTerminalAt(v)
	return _c
}

// SetNillableTerminalAt sets the "terminal_at" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableTerminalAt(v *time.Time) *VideoTaskCreate {
	if v != nil {
		_c.SetTerminalAt(*v)
	}
	return _c
}

// SetRefundedAt sets the "refunded_at" field.
func (_c *VideoTaskCreate) SetRefundedAt(v time.Time) *VideoTaskCreate {
	_c.mutation.SetRefundedAt(v)
	return _c
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableRefundedAt(v *time.Time) *VideoTaskCreate {
	if v != nil {
		_c.SetRefundedAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *VideoTaskCreate) SetLastError(v string) *VideoTaskCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableLastError(v *string) *VideoTaskCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VideoTaskCreate) SetCreatedAt(v time.Time) *VideoTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableCreatedAt(v *time.Time) *VideoTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VideoTaskCreate) SetUpdatedAt(v time.Time) *VideoTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableUpdatedAt(v *time.Time) *VideoTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the VideoTaskMutation object of the builder.
func (_c *VideoTaskCreate) Mutation() *VideoTaskMutation {
	return _c.mutation
}

// Save creates the VideoTask in the database.
func (_c *VideoTaskCreate) Save(ctx context.Context) (*VideoTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VideoTaskCreate) SaveX(ctx context.Context) *VideoTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VideoTaskCreate) defaults() {
	if _, ok := _c.mutation.RefundAmount(); !ok {
		v := videotask.DefaultRefundAmount
		_c.mutation.SetRefundAmount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := videotask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.NextPollAt(); !ok {
		v := videotask.DefaultNextPollAt()
		_c.mutation.SetNextPollAt(v)
	}
	if _, ok := _c.mutation.PollAttempts(); !ok {
		v := videotask.DefaultPollAttempts
		_c.mutation.SetPollAttempts(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := videotask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := videotask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VideoTaskCreate) check() error {
	if _, ok := _c.mutation.UpstreamTaskID(); !ok {
		return &ValidationError{Name: "upstream_task_id", err: errors.New(`ent: missing required field "VideoTask.upstream_task_id"`)}
	}
	if v, ok := _c.mutation.UpstreamTaskID(); ok {
		if err := videotask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BillingRequestID(); !ok {
		return &ValidationError{Name: "billing_request_id", err: errors.New(`ent: missing required field "VideoTask.billing_request_id"`)}
	}
	if v, ok := _c.mutation.BillingRequestID(); ok {
		if err := videotask.BillingRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "billing_request_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.billing_request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "VideoTask.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "VideoTask.api_key_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "VideoTask.account_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "VideoTask.group_id"`)}
	}
	if _, ok := _c.mutation.RefundAmount(); !ok {
		return &ValidationError{Name: "refund_amount", err: errors.New(`ent: missing required field "VideoTask.refund_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "VideoTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := videotask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NextPollAt(); !ok {
		return &ValidationError{Name: "next_poll_at", err: errors.New(`ent: missing required field "VideoTask.next_poll_at"`)}
	}
	if _, ok := _c.mutation.PollAttempts(); !ok {
		return &ValidationError{Name: "poll_attempts", err: errors.New(`ent: missing required field "VideoTask.poll_attempts"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VideoTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VideoTask.updated_at"`)}
	}
	return nil
}

func (_c *VideoTaskCreate) sqlSave(ctx context.Context) (*VideoTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VideoTaskCreate) createSpec() (*VideoTask, *sqlgraph.CreateSpec) {
	var (
		_node = &VideoTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(videotask.Table, sqlgraph.NewFieldSpec(videotask.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UpstreamTaskID(); ok {
		_spec.SetField(videotask.FieldUpstreamTaskID, field.TypeString, value)
		_node.UpstreamTaskID = value
	}
	if value, ok := _c.mutation.BillingRequestID(); ok {
		_spec.SetField(videotask.FieldBillingRequestID, field.TypeString, value)
		_node.BillingRequestID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(videotask.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(videotask.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(videotask.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(videotask.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.RefundAmount(); ok {
		_spec.SetField(videotask.FieldRefundAmount, field.TypeFloat64, value)
		_node.RefundAmount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(videotask.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.NextPollAt(); ok {
		_spec.SetField(videotask.FieldNextPollAt, field.TypeTime, value)
		_node.NextPollAt = value
	}
	if value, ok := _c.mutation.LockedUntil(); ok {
		_spec.SetField(videotask.FieldLockedUntil, field.TypeTime, value)
		_node.LockedUntil = &value
	}
	if value, ok := _c.mutation.PollAttempts(); ok {
		_spec.SetField(videotask.FieldPollAttempts, field.TypeInt, value)
		_node.PollAttempts = value
	}
	if value, ok := _c.mutation.TerminalAt(); ok {
		_spec.SetField(videotask.FieldTerminalAt, field.TypeTime, value)
		_node.TerminalAt = &value
	}
	if value, ok := _c.mutation.RefundedAt(); ok {
		_spec.SetField(videotask.FieldRefundedAt, field.TypeTime, value)
		_node.RefundedAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(videotask.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(videotask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(videotask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoTask.Create().
//		SetUpstreamTaskID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoTaskUpsert) {
//			SetUpstreamTaskID(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoTaskCreate) OnConflict(opts ...sql.ConflictOption) *VideoTaskUpsertOne {
	_c.conflict = opts
	return &VideoTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoTaskCreate) OnConflictColumns(columns ...string) *VideoTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoTaskUpsertOne{
		create: _c,
	}
}

type (
	// VideoTaskUpsertOne is the builder for "upsert"-ing
	//  one VideoTask node.
	VideoTaskUpsertOne struct {
		create *VideoTaskCreate
	}

	// VideoTaskUpsert is the "OnConflict" setter.
	VideoTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *VideoTaskUpsert) SetUpstreamTaskID(v string) *VideoTaskUpsert {
	u.Set(videotask.FieldUpstreamTaskID, v)
	return u
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateUpstreamTaskID() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldUpstreamTaskID)
	return u
}

// SetBillingRequestID sets the "billing_request_id" field.
func (u *VideoTaskUpsert) SetBillingRequestID(v string) *VideoTaskUpsert {
	u.Set(videotask.FieldBillingRequestID, v)
	return u
}

// UpdateBillingRequestID sets the "billing_request_id" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateBillingRequestID() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldBillingRequestID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *VideoTaskUpsert) SetUserID(v int64) *VideoTaskUpsert {
	u.Set(videotask.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateUserID() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *VideoTaskUpsert) AddUserID(v int64) *VideoTaskUpsert {
	u.Add(videotask.FieldUserID, v)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *VideoTaskUpsert) SetAPIKeyID(v int64) *VideoTaskUpsert {
	u.Set(videotask.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateAPIKeyID() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *VideoTaskUpsert) AddAPIKeyID(v int64) *VideoTaskUpsert {
	u.Add(videotask.FieldAPIKeyID, v)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *VideoTaskUpsert) SetAccountID(v int64) *VideoTaskUpsert {
	u.Set(videotask.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateAccountID() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *VideoTaskUpsert) AddAccountID(v int64) *VideoTaskUpsert {
	u.Add(videotask.FieldAccountID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *VideoTaskUpsert) SetGroupID(v int64) *VideoTaskUpsert {
	u.Set(videotask.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateGroupID() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *VideoTaskUpsert) AddGroupID(v int64) *VideoTaskUpsert {
	u.Add(videotask.FieldGroupID, v)
	return u
}

// SetRefundAmount sets the "refund_amount" field.
func (u *VideoTaskUpsert) SetRefundAmount(v float64) *VideoTaskUpsert {
	u.Set(videotask.FieldRefundAmount, v)
	return u
}

// UpdateRefundAmount sets the "refund_amount" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateRefundAmount() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldRefundAmount)
	return u
}

// AddRefundAmount adds v to the "refund_amount" field.
func (u *VideoTaskUpsert) AddRefundAmount(v float64) *VideoTaskUpsert {
	u.Add(videotask.FieldRefundAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *VideoTaskUpsert) SetStatus(v string) *VideoTaskUpsert {
	u.Set(videotask.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateStatus() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldStatus)
	return u
}

// SetNextPollAt sets the "next_poll_at" field.
func (u *VideoTaskUpsert) SetNextPollAt(v time.Time) *VideoTaskUpsert {
	u.Set(videotask.FieldNextPollAt, v)
	return u
}

// UpdateNextPollAt sets the "next_poll_at" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateNextPollAt() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldNextPollAt)
	return u
}

// SetLockedUntil sets the "locked_until" field.
func (u *VideoTaskUpsert) SetLockedUntil(v time.Time) *VideoTaskUpsert {
	u.Set(videotask.FieldLockedUntil, v)
	return u
}

// UpdateLockedUntil sets the "locked_until" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateLockedUntil() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldLockedUntil)
	return u
}

// ClearLockedUntil clears the value of the "locked_until" field.
func (u *VideoTaskUpsert) ClearLockedUntil() *VideoTaskUpsert {
	u.SetNull(videotask.FieldLockedUntil)
	return u
}

// SetPollAttempts sets the "poll_attempts" field.
func (u *VideoTaskUpsert) SetPollAttempts(v int) *VideoTaskUpsert {
	u.Set(videotask.FieldPollAttempts, v)
	return u
}

// UpdatePollAttempts sets the "poll_attempts" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdatePollAttempts() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldPollAttempts)
	return u
}

// AddPollAttempts adds v to the "poll_attempts" field.
func (u *VideoTaskUpsert) AddPollAttempts(v int) *VideoTaskUpsert {
	u.Add(videotask.FieldPollAttempts, v)
	return u
}

// SetTerminalAt sets the "terminal_at" field.
func (u *VideoTaskUpsert) SetTerminalAt(v time.Time) *VideoTaskUpsert {
	u.Set(videotask.FieldTerminalAt, v)
	return u
}

// UpdateTerminalAt sets the "terminal_at" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateTerminalAt() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldTerminalAt)
	return u
}

// ClearTerminalAt clears the value of the "terminal_at" field.
func (u *VideoTaskUpsert) ClearTerminalAt() *VideoTaskUpsert {
	u.SetNull(videotask.FieldTerminalAt)
	return u
}

// SetRefundedAt sets the "refunded_at" field.
func (u *VideoTaskUpsert) SetRefundedAt(v time.Time) *VideoTaskUpsert {
	u.Set(videotask.FieldRefundedAt, v)
	return u
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateRefundedAt() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldRefundedAt)
	return u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *VideoTaskUpsert) ClearRefundedAt() *VideoTaskUpsert {
	u.SetNull(videotask.FieldRefundedAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *VideoTaskUpsert) SetLastError(v string) *VideoTaskUpsert {
	u.Set(videotask.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateLastError() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *VideoTaskUpsert) ClearLastError() *VideoTaskUpsert {
	u.SetNull(videotask.FieldLastError)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoTaskUpsert) SetUpdatedAt(v time.Time) *VideoTaskUpsert {
	u.Set(videotask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateUpdatedAt() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoTaskUpsertOne) UpdateNewValues() *VideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(videotask.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VideoTaskUpsertOne) Ignore() *VideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoTaskUpsertOne) DoNothing() *VideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoTaskCreate.OnConflict
// documentation for more info.
func (u *VideoTaskUpsertOne) Update(set func(*VideoTaskUpsert)) *VideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *VideoTaskUpsertOne) SetUpstreamTaskID(v string) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUpstreamTaskID(v)
	})
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateUpstreamTaskID() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUpstreamTaskID()
	})
}

// SetBillingRequestID sets the "billing_request_id" field.
func (u *VideoTaskUpsertOne) SetBillingRequestID(v string) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetBillingRequestID(v)
	})
}

// UpdateBillingRequestID sets the "billing_request_id" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateBillingRequestID() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateBillingRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *VideoTaskUpsertOne) SetUserID(v int64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *VideoTaskUpsertOne) AddUserID(v int64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateUserID() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *VideoTaskUpsertOne) SetAPIKeyID(v int64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *VideoTaskUpsertOne) AddAPIKeyID(v int64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateAPIKeyID() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *VideoTaskUpsertOne) SetAccountID(v int64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *VideoTaskUpsertOne) AddAccountID(v int64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateAccountID() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *VideoTaskUpsertOne) SetGroupID(v int64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *VideoTaskUpsertOne) AddGroupID(v int64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateGroupID() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateGroupID()
	})
}

// SetRefundAmount sets the "refund_amount" field.
func (u *VideoTaskUpsertOne) SetRefundAmount(v float64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetRefundAmount(v)
	})
}

// AddRefundAmount adds v to the "refund_amount" field.
func (u *VideoTaskUpsertOne) AddRefundAmount(v float64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddRefundAmount(v)
	})
}

// UpdateRefundAmount sets the "refund_amount" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateRefundAmount() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateRefundAmount()
	})
}

// SetStatus sets the "status" field.
func (u *VideoTaskUpsertOne) SetStatus(v string) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateStatus() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetNextPollAt sets the "next_poll_at" field.
func (u *VideoTaskUpsertOne) SetNextPollAt(v time.Time) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetNextPollAt(v)
	})
}

// UpdateNextPollAt sets the "next_poll_at" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateNextPollAt() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateNextPollAt()
	})
}

// SetLockedUntil sets the "locked_until" field.
func (u *VideoTaskUpsertOne) SetLockedUntil(v time.Time) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetLockedUntil(v)
	})
}

// UpdateLockedUntil sets the "locked_until" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateLockedUntil() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateLockedUntil()
	})
}

// ClearLockedUntil clears the value of the "locked_until" field.
func (u *VideoTaskUpsertOne) ClearLockedUntil() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearLockedUntil()
	})
}

// SetPollAttempts sets the "poll_attempts" field.
func (u *VideoTaskUpsertOne) SetPollAttempts(v int) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetPollAttempts(v)
	})
}

// AddPollAttempts adds v to the "poll_attempts" field.
func (u *VideoTaskUpsertOne) AddPollAttempts(v int) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddPollAttempts(v)
	})
}

// UpdatePollAttempts sets the "poll_attempts" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdatePollAttempts() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdatePollAttempts()
	})
}

// SetTerminalAt sets the "terminal_at" field.
func (u *VideoTaskUpsertOne) SetTerminalAt(v time.Time) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetTerminalAt(v)
	})
}

// UpdateTerminalAt sets the "terminal_at" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateTerminalAt() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateTerminalAt()
	})
}

// ClearTerminalAt clears the value of the "terminal_at" field.
func (u *VideoTaskUpsertOne) ClearTerminalAt() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearTerminalAt()
	})
}

// SetRefundedAt sets the "refunded_at" field.
func (u *VideoTaskUpsertOne) SetRefundedAt(v time.Time) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetRefundedAt(v)
	})
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateRefundedAt() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateRefundedAt()
	})
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *VideoTaskUpsertOne) ClearRefundedAt() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearRefundedAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *VideoTaskUpsertOne) SetLastError(v string) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateLastError() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *VideoTaskUpsertOne) ClearLastError() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearLastError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoTaskUpsertOne) SetUpdatedAt(v time.Time) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateUpdatedAt() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *VideoTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VideoTaskUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VideoTaskUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VideoTaskCreateBulk is the builder for creating many VideoTask entities in bulk.
type VideoTaskCreateBulk struct {
	config
	err      error
	builders []*VideoTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the VideoTask entities in the database.
func (_c *VideoTaskCreateBulk) Save(ctx context.Context) ([]*VideoTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VideoTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VideoTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VideoTaskCreateBulk) SaveX(ctx context.Context) []*VideoTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoTaskUpsert) {
//			SetUpstreamTaskID(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *VideoTaskUpsertBulk {
	_c.conflict = opts
	return &VideoTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoTaskCreateBulk) OnConflictColumns(columns ...string) *VideoTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoTaskUpsertBulk{
		create: _c,
	}
}

// VideoTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of VideoTask nodes.
type VideoTaskUpsertBulk struct {
	create *VideoTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoTaskUpsertBulk) UpdateNewValues() *VideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(videotask.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VideoTaskUpsertBulk) Ignore() *VideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoTaskUpsertBulk) DoNothing() *VideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoTaskCreateBulk.OnConflict
// documentation for more info.
func (u *VideoTaskUpsertBulk) Update(set func(*VideoTaskUpsert)) *VideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *VideoTaskUpsertBulk) SetUpstreamTaskID(v string) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUpstreamTaskID(v)
	})
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateUpstreamTaskID() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUpstreamTaskID()
	})
}

// SetBillingRequestID sets the "billing_request_id" field.
func (u *VideoTaskUpsertBulk) SetBillingRequestID(v string) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetBillingRequestID(v)
	})
}

// UpdateBillingRequestID sets the "billing_request_id" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateBillingRequestID() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateBillingRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *VideoTaskUpsertBulk) SetUserID(v int64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *VideoTaskUpsertBulk) AddUserID(v int64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateUserID() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *VideoTaskUpsertBulk) SetAPIKeyID(v int64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *VideoTaskUpsertBulk) AddAPIKeyID(v int64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateAPIKeyID() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *VideoTaskUpsertBulk) SetAccountID(v int64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *VideoTaskUpsertBulk) AddAccountID(v int64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateAccountID() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *VideoTaskUpsertBulk) SetGroupID(v int64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *VideoTaskUpsertBulk) AddGroupID(v int64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateGroupID() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateGroupID()
	})
}

// SetRefundAmount sets the "refund_amount" field.
func (u *VideoTaskUpsertBulk) SetRefundAmount(v float64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetRefundAmount(v)
	})
}

// AddRefundAmount adds v to the "refund_amount" field.
func (u *VideoTaskUpsertBulk) AddRefundAmount(v float64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddRefundAmount(v)
	})
}

// UpdateRefundAmount sets the "refund_amount" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateRefundAmount() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateRefundAmount()
	})
}

// SetStatus sets the "status" field.
func (u *VideoTaskUpsertBulk) SetStatus(v string) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateStatus() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetNextPollAt sets the "next_poll_at" field.
func (u *VideoTaskUpsertBulk) SetNextPollAt(v time.Time) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetNextPollAt(v)
	})
}

// UpdateNextPollAt sets the "next_poll_at" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateNextPollAt() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateNextPollAt()
	})
}

// SetLockedUntil sets the "locked_until" field.
func (u *VideoTaskUpsertBulk) SetLockedUntil(v time.Time) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetLockedUntil(v)
	})
}

// UpdateLockedUntil sets the "locked_until" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateLockedUntil() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateLockedUntil()
	})
}

// ClearLockedUntil clears the value of the "locked_until" field.
func (u *VideoTaskUpsertBulk) ClearLockedUntil() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearLockedUntil()
	})
}

// SetPollAttempts sets the "poll_attempts" field.
func (u *VideoTaskUpsertBulk) SetPollAttempts(v int) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetPollAttempts(v)
	})
}

// AddPollAttempts adds v to the "poll_attempts" field.
func (u *VideoTaskUpsertBulk) AddPollAttempts(v int) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddPollAttempts(v)
	})
}

// UpdatePollAttempts sets the "poll_attempts" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdatePollAttempts() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdatePollAttempts()
	})
}

// SetTerminalAt sets the "terminal_at" field.
func (u *VideoTaskUpsertBulk) SetTerminalAt(v time.Time) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetTerminalAt(v)
	})
}

// UpdateTerminalAt sets the "terminal_at" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateTerminalAt() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateTerminalAt()
	})
}

// ClearTerminalAt clears the value of the "terminal_at" field.
func (u *VideoTaskUpsertBulk) ClearTerminalAt() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearTerminalAt()
	})
}

// SetRefundedAt sets the "refunded_at" field.
func (u *VideoTaskUpsertBulk) SetRefundedAt(v time.Time) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetRefundedAt(v)
	})
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateRefundedAt() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateRefundedAt()
	})
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *VideoTaskUpsertBulk) ClearRefundedAt() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearRefundedAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *VideoTaskUpsertBulk) SetLastError(v string) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateLastError() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *VideoTaskUpsertBulk) ClearLastError() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearLastError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoTaskUpsertBulk) SetUpdatedAt(v time.Time) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateUpdatedAt() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *VideoTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VideoTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
