// Code generated by ent, DO NOT EDIT.

package supportticketread

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLTE(FieldID, id))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldTicketID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldUserID, v))
}

// LastReadMessageID applies equality check predicate on the "last_read_message_id" field. It's identical to LastReadMessageIDEQ.
func LastReadMessageID(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldLastReadMessageID, v))
}

// ReadAt applies equality check predicate on the "read_at" field. It's identical to ReadAtEQ.
func ReadAt(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldReadAt, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNotIn(FieldTicketID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNotIn(FieldUserID, vs...))
}

// LastReadMessageIDEQ applies the EQ predicate on the "last_read_message_id" field.
func LastReadMessageIDEQ(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldLastReadMessageID, v))
}

// LastReadMessageIDNEQ applies the NEQ predicate on the "last_read_message_id" field.
func LastReadMessageIDNEQ(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNEQ(FieldLastReadMessageID, v))
}

// LastReadMessageIDIn applies the In predicate on the "last_read_message_id" field.
func LastReadMessageIDIn(vs ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldIn(FieldLastReadMessageID, vs...))
}

// LastReadMessageIDNotIn applies the NotIn predicate on the "last_read_message_id" field.
func LastReadMessageIDNotIn(vs ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNotIn(FieldLastReadMessageID, vs...))
}

// LastReadMessageIDGT applies the GT predicate on the "last_read_message_id" field.
func LastReadMessageIDGT(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGT(FieldLastReadMessageID, v))
}

// LastReadMessageIDGTE applies the GTE predicate on the "last_read_message_id" field.
func LastReadMessageIDGTE(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGTE(FieldLastReadMessageID, v))
}

// LastReadMessageIDLT applies the LT predicate on the "last_read_message_id" field.
func LastReadMessageIDLT(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLT(FieldLastReadMessageID, v))
}

// LastReadMessageIDLTE applies the LTE predicate on the "last_read_message_id" field.
func LastReadMessageIDLTE(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLTE(FieldLastReadMessageID, v))
}

// ReadAtEQ applies the EQ predicate on the "read_at" field.
func ReadAtEQ(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldReadAt, v))
}

// ReadAtNEQ applies the NEQ predicate on the "read_at" field.
func ReadAtNEQ(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNEQ(FieldReadAt, v))
}

// ReadAtIn applies the In predicate on the "read_at" field.
func ReadAtIn(vs ...time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldIn(FieldReadAt, vs...))
}

// ReadAtNotIn applies the NotIn predicate on the "read_at" field.
func ReadAtNotIn(vs ...time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNotIn(FieldReadAt, vs...))
}

// ReadAtGT applies the GT predicate on the "read_at" field.
func ReadAtGT(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGT(FieldReadAt, v))
}

// ReadAtGTE applies the GTE predicate on the "read_at" field.
func ReadAtGTE(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGTE(FieldReadAt, v))
}

// ReadAtLT applies the LT predicate on the "read_at" field.
func ReadAtLT(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLT(FieldReadAt, v))
}

// ReadAtLTE applies the LTE predicate on the "read_at" field.
func ReadAtLTE(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLTE(FieldReadAt, v))
}

// HasTicket applies the HasEdge predicate on the "ticket" edge.
func HasTicket() predicate.SupportTicketRead {
	return predicate.SupportTicketRead(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketWith applies the HasEdge predicate on the "ticket" edge with a given conditions (other predicates).
func HasTicketWith(preds ...predicate.SupportTicket) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(func(s *sql.Selector) {
		step := newTicketStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SupportTicketRead {
	return predicate.SupportTicketRead(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupportTicketRead) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupportTicketRead) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupportTicketRead) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.NotPredicates(p))
}
