package service

import infraerrors "github.com/Wei-Shaw/sub2api/internal/pkg/errors"

var (
	ErrAlreadyInTeam                   = infraerrors.Conflict("ALREADY_IN_TEAM", "user is already in a team")
	ErrTeamNotFound                    = infraerrors.NotFound("TEAM_NOT_FOUND", "team not found")
	ErrInviteCodeInvalid               = infraerrors.BadRequest("INVITE_CODE_INVALID", "invalid invite code")
	ErrInviteCodeExists                = infraerrors.Conflict("INVITE_CODE_EXISTS", "invite code already exists")
	ErrNotTeamOwner                    = infraerrors.Forbidden("NOT_TEAM_OWNER", "only team owner can perform this action")
	ErrNotInTeam                       = infraerrors.Forbidden("NOT_IN_TEAM", "user is not in a team")
	ErrCannotRemoveOwner               = infraerrors.Forbidden("CANNOT_REMOVE_OWNER", "cannot remove team owner")
	ErrCannotLeaveAsOwner              = infraerrors.Forbidden("CANNOT_LEAVE_AS_OWNER", "team owner cannot leave the team")
	ErrTeamMemberNotFound              = infraerrors.NotFound("TEAM_MEMBER_NOT_FOUND", "team member not found")
	ErrInsufficientTeamBalance         = infraerrors.BadRequest("INSUFFICIENT_TEAM_BALANCE", "insufficient balance for transfer")
	ErrInsufficientTeamFund            = infraerrors.BadRequest("INSUFFICIENT_TEAM_FUND", "insufficient team fund balance")
	ErrInvalidFundAmount               = infraerrors.BadRequest("INVALID_FUND_AMOUNT", "fund amount must be greater than zero")
	ErrTeamPasswordIncorrect           = infraerrors.BadRequest("TEAM_PASSWORD_INCORRECT", "incorrect password")
	ErrTeamApplicationPending          = infraerrors.Conflict("TEAM_APPLICATION_PENDING", "a team application is already pending")
	ErrTeamApplicationNotFound         = infraerrors.NotFound("TEAM_APPLICATION_NOT_FOUND", "team application not found")
	ErrTeamApplicationResolved         = infraerrors.Conflict("TEAM_APPLICATION_RESOLVED", "team application has already been reviewed")
	ErrTeamThresholdNotMet             = infraerrors.Forbidden("TEAM_THRESHOLD_NOT_MET", "team creation requirements are not met")
	ErrTeamWaiverReasonRequired        = infraerrors.BadRequest("TEAM_WAIVER_REASON_REQUIRED", "a review reason is required when waiving requirements")
	ErrTeamJoinPending                 = infraerrors.Conflict("TEAM_JOIN_PENDING", "a team join request is already pending")
	ErrTeamJoinNotFound                = infraerrors.NotFound("TEAM_JOIN_NOT_FOUND", "team join request not found")
	ErrTeamJoinResolved                = infraerrors.Conflict("TEAM_JOIN_RESOLVED", "team join request has already been reviewed")
	ErrTeamFull                        = infraerrors.Conflict("TEAM_FULL", "team member limit has been reached")
	ErrTeamFrozen                      = infraerrors.Forbidden("TEAM_FROZEN", "team is frozen")
	ErrTeamReviewRequired              = infraerrors.Forbidden("TEAM_REVIEW_REQUIRED", "team must be reviewed by an administrator before expansion")
	ErrTeamUpgradeUnavailable          = infraerrors.BadRequest("TEAM_UPGRADE_UNAVAILABLE", "no higher team level requirements are currently met")
	ErrInvalidTeamLimit                = infraerrors.BadRequest("INVALID_TEAM_LIMIT", "team member limit is invalid")
	ErrInsufficientTransferableBalance = infraerrors.BadRequest("INSUFFICIENT_TRANSFERABLE_BALANCE", "insufficient transferable balance")
	ErrInvalidTeamName                 = infraerrors.BadRequest("INVALID_TEAM_NAME", "team name is invalid")
	ErrInvalidTeamSettings             = infraerrors.BadRequest("INVALID_TEAM_SETTINGS", "team governance settings are invalid")
)
