// Code generated by ent, DO NOT EDIT.

package supportticketmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldID, id))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// AuthorID applies equality check predicate on the "author_id" field. It's identical to AuthorIDEQ.
func AuthorID(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorID, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldKind, v))
}

// Visibility applies equality check predicate on the "visibility" field. It's identical to VisibilityEQ.
func Visibility(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldVisibility, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldBody, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldTicketID, vs...))
}

// AuthorIDEQ applies the EQ predicate on the "author_id" field.
func AuthorIDEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorIDNEQ applies the NEQ predicate on the "author_id" field.
func AuthorIDNEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldAuthorID, v))
}

// AuthorIDIn applies the In predicate on the "author_id" field.
func AuthorIDIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldAuthorID, vs...))
}

// AuthorIDNotIn applies the NotIn predicate on the "author_id" field.
func AuthorIDNotIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldAuthorID, vs...))
}

// AuthorIDIsNil applies the IsNil predicate on the "author_id" field.
func AuthorIDIsNil() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIsNull(FieldAuthorID))
}

// AuthorIDNotNil applies the NotNil predicate on the "author_id" field.
func AuthorIDNotNil() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotNull(FieldAuthorID))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldKind, v))
}

// VisibilityEQ applies the EQ predicate on the "visibility" field.
func VisibilityEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldVisibility, v))
}

// VisibilityNEQ applies the NEQ predicate on the "visibility" field.
func VisibilityNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldVisibility, v))
}

// VisibilityIn applies the In predicate on the "visibility" field.
func VisibilityIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldVisibility, vs...))
}

// VisibilityNotIn applies the NotIn predicate on the "visibility" field.
func VisibilityNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldVisibility, vs...))
}

// VisibilityGT applies the GT predicate on the "visibility" field.
func VisibilityGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldVisibility, v))
}

// VisibilityGTE applies the GTE predicate on the "visibility" field.
func VisibilityGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldVisibility, v))
}

// VisibilityLT applies the LT predicate on the "visibility" field.
func VisibilityLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldVisibility, v))
}

// VisibilityLTE applies the LTE predicate on the "visibility" field.
func VisibilityLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldVisibility, v))
}

// VisibilityContains applies the Contains predicate on the "visibility" field.
func VisibilityContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldVisibility, v))
}

// VisibilityHasPrefix applies the HasPrefix predicate on the "visibility" field.
func VisibilityHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldVisibility, v))
}

// VisibilityHasSuffix applies the HasSuffix predicate on the "visibility" field.
func VisibilityHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldVisibility, v))
}

// VisibilityEqualFold applies the EqualFold predicate on the "visibility" field.
func VisibilityEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldVisibility, v))
}

// VisibilityContainsFold applies the ContainsFold predicate on the "visibility" field.
func VisibilityContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldVisibility, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldBody, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTicket applies the HasEdge predicate on the "ticket" edge.
func HasTicket() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketWith applies the HasEdge predicate on the "ticket" edge with a given conditions (other predicates).
func HasTicketWith(preds ...predicate.SupportTicket) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(func(s *sql.Selector) {
		step := newTicketStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAuthor applies the HasEdge predicate on the "author" edge.
func HasAuthor() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AuthorTable, AuthorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthorWith applies the HasEdge predicate on the "author" edge with a given conditions (other predicates).
func HasAuthorWith(preds ...predicate.User) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(func(s *sql.Selector) {
		step := newAuthorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttachments applies the HasEdge predicate on the "attachments" edge.
func HasAttachments() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttachmentsWith applies the HasEdge predicate on the "attachments" edge with a given conditions (other predicates).
func HasAttachmentsWith(preds ...predicate.SupportTicketAttachment) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(func(s *sql.Selector) {
		step := newAttachmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupportTicketMessage) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupportTicketMessage) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupportTicketMessage) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.NotPredicates(p))
}
